[package]
name = "openvibes-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
openvibes-console = { path = "../openvibes-console" }
chrono.workspace = true
clap.workspace = true
platform-config = { path = "../platform-config" }
platform-pki = { path = "../platform-pki" }
ring.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
openvibes-core.workspace = true
openvibes-rules.workspace = true
serde_json.workspace = true
sha2.workspace = true
platform-store = { path = "../platform-store" }
serde.workspace = true
rpassword = "=7.5.4"
tokio.workspace = true
zeroize = "=1.9.0"

[lints]
workspace = true
