[package]
name = "openvibes-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
platform-assistant = { path = "../platform-assistant" }
openvibes-llm = { path = "../openvibes-llm" }
platform-config = { path = "../platform-config" }
platform-pki = { path = "../platform-pki" }
ring.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
openvibes-core.workspace = true
openvibes-rules.workspace = true
serde_json.workspace = true
sha2.workspace = true
platform-store = { path = "../platform-store" }
openvibes-vulns = { path = "../openvibes-vulns" }
serde.workspace = true
tokio.workspace = true

[lints]
workspace = true

[dev-dependencies]
zip = { version = "8.6.0", default-features = false }
