/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access-control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_access_inventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agent_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agent_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agent_certificates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_audit_retention"];
        put: operations["update_authenticated_audit_retention"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_finding_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/history/{observed_day}/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_finding_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_latest_findings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/latest/{agent_id}/{rule_set_id}/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_latest_finding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_finding_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the current authenticated browser session.
         * @description The C0 router deliberately returns a bounded failure instead of creating a
         *     temporary unauthenticated or implicitly privileged session.
         */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/preauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preauth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Manual asset group and exact selectors. */
        AccessAssetGroup: {
            /** @description Stable group identifier. */
            asset_group_id: string;
            /** @description Operator-facing group name. */
            name: string;
            /** @description Exact `key=value` selectors, all of which must match. */
            selectors: string[];
        };
        /** @description Active local-user role assignment. */
        AccessBinding: {
            /** @description Asset group id; null denotes global scope. */
            asset_group_id?: string | null;
            /** @description Asset group name, when scoped. */
            asset_group_name?: string | null;
            /** @description Stable binding identifier. */
            binding_id: string;
            /** @description RFC 3339 creation time. */
            created_at: string;
            /** @description Actor who created the binding. */
            created_by: string;
            /** @description Display label. */
            display_name: string;
            /** @description Role identifier. */
            role_id: string;
            /** @description Stable local user identifier. */
            user_id: string;
            /** @description Local username. */
            username: string;
        };
        /** @description Read-only review of roles, bindings, and asset groups. */
        AccessInventory: {
            /** @description Manual asset groups and their exact tag selectors. */
            asset_groups: components["schemas"]["AccessAssetGroup"][];
            /** @description Active local-user role bindings. */
            bindings: components["schemas"]["AccessBinding"][];
            /** @description All available roles and granted permission identifiers. */
            roles: components["schemas"]["AccessRole"][];
        };
        /** @description Role and permission mapping. */
        AccessRole: {
            /** @description Whether this is a built-in role. */
            builtin: boolean;
            /** @description Operator-facing name. */
            display_name: string;
            /** @description Permission identifiers. */
            permissions: string[];
            /** @description Stable role identifier. */
            role_id: string;
        };
        /** @description Agent and current certificate metadata. */
        AgentDetail: components["schemas"]["AgentView"] & {
            /** @description Certificate metadata for the agent. */
            certificates: components["schemas"]["CertificateView"][];
        };
        /** @description A page of agents using the shared cursor response shape. */
        AgentPage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["AgentView"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /**
         * @description Lifecycle state reported for an enrolled agent.
         * @enum {string}
         */
        AgentStatus: "active" | "stale" | "revoked";
        /** @description Fleet counts visible to the current principal. */
        AgentSummary: {
            /**
             * Format: int64
             * @description Number of visible active agents.
             */
            active: number;
            /**
             * Format: int64
             * @description Number of visible revoked agents.
             */
            revoked: number;
            /**
             * Format: int64
             * @description Number of visible stale agents.
             */
            stale: number;
            /**
             * Format: int64
             * @description Number of visible enrolled agents.
             */
            total: number;
        };
        /** @description Operator-facing agent fields shared by the read API and seeded server. */
        AgentView: {
            /** @description Reported agent capabilities. */
            capabilities: string[];
            /** @description RFC 3339 enrollment time. */
            enrolled_at: string;
            /** @description Latest hostname reported by an authenticated heartbeat; this is an operator label. */
            hostname?: string | null;
            /** @description Stable platform agent identifier. */
            id: string;
            /** @description RFC 3339 time of the latest heartbeat, if present. */
            last_seen_at?: string | null;
            /** @description RFC 3339 revocation time, if revoked. */
            revoked_at?: string | null;
            /** @description Reported scanner version, if present. */
            scanner_version?: string | null;
            /** @description Current lifecycle state. */
            status: components["schemas"]["AgentStatus"];
        };
        /** @description Bounded audit-event page with an opaque continuation cursor. */
        AuditEventPage: {
            /** @description Events in descending timestamp order. */
            items: components["schemas"]["AuditEventView"][];
            /** @description Opaque cursor for the next page, if present. */
            next_cursor?: string | null;
        };
        /** @description One safe audit event in a bounded audit search. */
        AuditEventView: {
            /** @description Stable action code. */
            action: string;
            /** @description Operator-facing actor label. */
            actor: string;
            /** @description Stable actor id. */
            actor_id?: string | null;
            /** @description Actor kind and stable id. */
            actor_kind?: string | null;
            /** @description RFC 3339 event timestamp. */
            at: string;
            /** @description Authentication method, when present. */
            authentication_method?: string | null;
            /** @description Stable database event identifier. */
            id: string;
            /** @description Safe reason code. */
            reason_code?: string | null;
            /** @description Request correlation id, when present. */
            request_id?: string | null;
            /** @description Event result code. */
            result: string;
            /** @description Safe target label, when present. */
            target?: string | null;
            /** @description Stable target id. */
            target_id?: string | null;
            /** @description Target kind and stable id. */
            target_kind?: string | null;
        };
        /** @description Current administrator-controlled audit retention policy. */
        AuditRetentionPolicy: {
            /**
             * Format: int32
             * @description Number of days kept after the next maintenance run.
             */
            retention_days: number;
            /** @description RFC 3339 update instant. */
            updated_at: string;
            /** @description Local user id that last changed the policy. */
            updated_by: string;
            /**
             * Format: int64
             * @description Version for conditional updates.
             */
            version: number;
        };
        /**
         * @description Authentication assurance reached by the current browser session.
         * @enum {string}
         */
        AuthenticationLevel: "single_factor" | "multi_factor";
        /**
         * @description Authentication mechanism that established a browser session.
         * @enum {string}
         */
        AuthenticationMethod: "local_password" | "oidc" | "saml";
        /** @description A page of certificate metadata using the shared cursor response shape. */
        CertificatePage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["CertificateView"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /** @description Certificate metadata exposed in an agent detail response. */
        CertificateView: {
            /** @description RFC 3339 certificate issuance time. */
            issued_at: string;
            /** @description RFC 3339 certificate expiry time. */
            not_after: string;
            /** @description RFC 3339 certificate validity start. */
            not_before: string;
            /** @description Certificate serial rendered as hexadecimal. */
            serial: string;
        };
        /** @description Validated cursor and limit accepted by cursor-paginated collection routes. */
        CursorPagination: {
            cursor?: string | null;
            /**
             * Format: int32
             * @default 50
             */
            limit: number;
        };
        /** @description One effective capability returned to the browser. */
        EffectiveCapability: {
            /** @description Permission granted to the current principal. */
            permission: components["schemas"]["Permission"];
            /** @description Effective global or asset-group scope for the permission. */
            scope: components["schemas"]["PermissionScope"];
        };
        /** @description Safe validation detail for one request field. */
        FieldError: {
            /** @description Stable machine-readable validation code. */
            code: string;
            /** @description Stable JSON field name or dotted field path. */
            field: string;
            /** @description Bounded operator-facing explanation. */
            message: string;
        };
        /** @description One historical observation event. */
        FindingHistoryEntry: {
            /** @description Agent associated with this event. */
            agent_id: string;
            /** @description Whether the observation was received through an authenticated agent. */
            authenticated: boolean;
            /**
             * Format: int32
             * @description Confidence as a percentage from 0 through 100.
             */
            confidence: number;
            /** @description Evidence key/value strings from the observation. */
            evidence: string[];
            /** @description Finding identifier from the partitioned event table. */
            id: string;
            /** @description Message recorded for this observation. */
            message: string;
            /** @description RFC 3339 time the agent or importer observed this finding. */
            observed_at: string;
            /** @description UTC partition day used for stable event lookup. */
            observed_day: string;
            /** @description Observation provenance. */
            origin: components["schemas"]["FindingOrigin"];
            /** @description RFC 3339 time the platform received this observation. */
            received_at: string;
            /** @description Rule identifier within the rule set. */
            rule_id: string;
            /** @description Rule set that produced the event, or `~unknown` for legacy data. */
            rule_set_id: string;
            /**
             * Format: int64
             * @description Signed rule version.
             */
            rule_version: number;
            /** @description Scan that produced the observation. */
            scan_id: string;
            /** @description Severity recorded for this observation. */
            severity: components["schemas"]["Severity"];
        };
        /** @description A page of historical observation events using the shared cursor response shape. */
        FindingHistoryPage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["FindingHistoryEntry"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /**
         * @description Provenance of a stored observation.
         * @enum {string}
         */
        FindingOrigin: "online" | "import";
        /** @description A page of latest observations using the shared cursor response shape. */
        FindingPage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["FindingView"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /** @description Counts for the latest observation rows visible to the current principal. */
        FindingSummary: {
            /**
             * Format: int64
             * @description Visible critical latest observations.
             */
            critical: number;
            /**
             * Format: int64
             * @description Visible high latest observations.
             */
            high: number;
            /**
             * Format: int64
             * @description Number of visible agents with at least one latest observation.
             */
            impacted_agents: number;
            /**
             * Format: int64
             * @description Visible low latest observations.
             */
            low: number;
            /**
             * Format: int64
             * @description Visible medium latest observations.
             */
            medium: number;
            /**
             * Format: int64
             * @description Number of visible latest observation rows.
             */
            total: number;
        };
        /** @description Latest observation state for one agent, rule set, and rule. */
        FindingView: {
            /** @description Agent associated with this observation. */
            agent_id: string;
            /** @description Whether the observation was received through an authenticated agent. */
            authenticated: boolean;
            /**
             * Format: int32
             * @description Confidence as a percentage from 0 through 100.
             */
            confidence: number;
            /** @description Evidence key/value strings from the observation. */
            evidence: string[];
            /** @description RFC 3339 time of the first observation. */
            first_observed_at: string;
            /** @description Latest hostname reported by the agent; this is an operator label. */
            hostname?: string | null;
            /** @description Stable latest-finding identifier. */
            id: string;
            /** @description RFC 3339 time of the latest observation. */
            last_observed_at: string;
            /** @description Latest observation message. */
            message: string;
            /** @description Observation provenance. */
            origin: components["schemas"]["FindingOrigin"];
            /** @description RFC 3339 time the platform received this observation. */
            received_at: string;
            /** @description Rule identifier within the rule set. */
            rule_id: string;
            /** @description Rule set that produced the finding, or `~unknown` for legacy data. */
            rule_set_id: string;
            /**
             * Format: int64
             * @description Signed rule version.
             */
            rule_version: number;
            /** @description Scan that produced the observation. */
            scan_id: string;
            /** @description Latest observed severity. */
            severity: components["schemas"]["Severity"];
        };
        /** @description One-use local login request. The password is never echoed by the API. */
        LoginRequest: {
            /**
             * Format: password
             * @description Password supplied over the configured secure transport.
             */
            password: string;
            /** @description Canonical local username (case is normalized by the server). */
            username: string;
        };
        /** @description Acknowledgement returned after a local password login succeeds. */
        LoginResponse: {
            /** @description Always true for the successful response; the session cookie is set separately. */
            authenticated: boolean;
        };
        /**
         * @description Stable console permission identifiers.
         * @enum {string}
         */
        Permission: "agents.read" | "agents.revoke" | "findings.read" | "findings.triage" | "tokens.read" | "tokens.create" | "tokens.revoke" | "rules.read" | "rules.upload" | "audit.read" | "audit.export" | "audit.retention.manage" | "rbac.read" | "rbac.manage" | "asset_groups.manage" | "service_accounts.read" | "service_accounts.manage";
        /** @description Effective object scope attached to one permission. */
        PermissionScope: {
            /** @enum {string} */
            kind: "global";
        } | {
            /** @description Stable asset-group identifiers selected by the binding resolver. */
            asset_group_ids: string[];
            /** @enum {string} */
            kind: "asset_groups";
        };
        /** @description CSRF challenge returned before local password login. */
        PreauthResponse: {
            /** @description One-use value required in `X-CSRF-Token` on the login request. */
            csrf_token: string;
        };
        /** @description Stable RFC Problem Details-style error response used by the console API. */
        ProblemDetails: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Bounded request-field errors when validation can safely identify them. */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** @description Process-local correlation identifier. */
            request_id: string;
            /**
             * Format: int32
             * @description HTTP status code.
             */
            status: number;
            /** @description Short human-readable error title. */
            title: string;
        };
        /** @description Human principal represented by an authenticated browser session. */
        SessionPrincipal: {
            /** @description Operator-facing display label. */
            display_name: string;
            /** @description Stable local or federated user identifier. */
            id: string;
            /** @description Local username when the identity has one. */
            username?: string | null;
        };
        /** @description Successful response from `GET /api/v1/session` for an active session. */
        SessionResponse: {
            /**
             * Format: date-time
             * @description RFC 3339 absolute session expiry instant.
             */
            absolute_expires_at: string;
            /** @description Assurance reached by the current session. */
            authentication_level: components["schemas"]["AuthenticationLevel"];
            /** @description Mechanism that established the session. */
            authentication_method: components["schemas"]["AuthenticationMethod"];
            /** @description Effective permissions and their scopes, resolved for this request. */
            capabilities: components["schemas"]["EffectiveCapability"][];
            /** @description Per-session value required in `X-CSRF-Token` on unsafe browser requests. */
            csrf_token: string;
            /**
             * Format: date-time
             * @description RFC 3339 instant when idle expiry occurs if the session is not used.
             */
            idle_expires_at: string;
            /** @description Current human principal. Service-account tokens cannot call this route. */
            principal: components["schemas"]["SessionPrincipal"];
        };
        /**
         * @description Severity attached to the latest observation for a rule.
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /** @description Request body for changing audit retention. */
        UpdateAuditRetentionRequest: {
            /**
             * Format: int32
             * @description Retention window in days, from 1 through 36500.
             */
            retention_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authenticated_access_inventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles, active bindings, and asset groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessInventory"];
                };
            };
        };
    };
    authenticated_agents: {
        parameters: {
            query?: {
                /** @description active, stale, or revoked */
                state?: string;
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size from 1 to 100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope-filtered agent page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_agent_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent counts visible to the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_agent_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible agent detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_agent_certificates: {
        parameters: {
            query?: {
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size from 1 to 100 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Stable agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible certificate metadata page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificatePage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_audit_events: {
        parameters: {
            query: {
                /** @description Inclusive RFC3339 lower bound */
                since: string;
                /** @description Exclusive RFC3339 upper bound */
                until?: string;
                actor?: string;
                action?: string;
                result?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe audit event page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
        };
    };
    authenticated_audit_retention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current audit retention policy */
            200: {
                headers: {
                    /** @description Policy version */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRetentionPolicy"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    update_authenticated_audit_retention: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted policy version from ETag */
                "If-Match": string;
                /** @description Must exactly match configured origin */
                Origin: string;
                /** @description Session synchronizer token */
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAuditRetentionRequest"];
            };
        };
        responses: {
            /** @description Updated retention policy */
            200: {
                headers: {
                    /** @description New policy version */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRetentionPolicy"];
                };
            };
            /** @description Invalid retention value or request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Origin, CSRF, or permission check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Policy version is stale */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description If-Match is required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Update unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_finding_history: {
        parameters: {
            query: {
                /** @description Required RFC 3339 lower bound for partition pruning */
                since: string;
                /** @description Exact agent filter */
                agent_id?: string;
                /** @description Exact rule-set filter; ~unknown selects legacy rows */
                rule_set_id?: string;
                /** @description Exact rule filter */
                rule_id?: string;
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size from 1 to 100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope-filtered finding history page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingHistoryPage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_finding_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UTC partition date */
                observed_day: string;
                /** @description Stable finding identifier */
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible immutable finding event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingHistoryEntry"];
                };
            };
            /** @description Invalid partition date */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Finding event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_latest_findings: {
        parameters: {
            query?: {
                /** @description critical, high, medium, or low */
                severity?: string;
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size from 1 to 100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope-filtered latest finding page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_latest_finding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable agent identifier */
                agent_id: string;
                /** @description Rule set id or reserved ~unknown */
                rule_set_id: string;
                /** @description Rule identifier */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible latest observation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingView"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Finding not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_finding_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope-filtered latest finding counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingSummary"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated browser session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Authentication is not implemented until C3 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured public origin */
                Origin: string;
                /** @description One-use token returned by pre-authentication */
                "X-CSRF-Token": string;
                /** @description Pre-auth and browser-binding cookies */
                Cookie: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; sets an opaque session cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Malformed authentication request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Generic invalid credentials response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Origin or CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication unavailable or busy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured public origin */
                Origin: string;
                /** @description Synchronizer token returned by the session route */
                "X-CSRF-Token": string;
                /** @description Opaque browser session cookie */
                Cookie: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Origin or CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    preauth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-use login challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreauthResponse"];
                };
            };
            /** @description Authentication unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
