/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the authenticated browser session once C3 authentication exists.
         * @description C0 deliberately returns a bounded failure instead of creating a temporary
         *     unauthenticated or implicitly privileged session.
         */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Authentication assurance reached by the current browser session.
         * @enum {string}
         */
        AuthenticationLevel: "single_factor" | "multi_factor";
        /**
         * @description Authentication mechanism that established a browser session.
         * @enum {string}
         */
        AuthenticationMethod: "local_password" | "oidc" | "saml";
        /** @description Validated cursor and limit accepted by cursor-paginated collection routes. */
        CursorPagination: {
            cursor?: string | null;
            /**
             * Format: int32
             * @default 50
             */
            limit: number;
        };
        /** @description One effective capability returned to the browser. */
        EffectiveCapability: {
            /** @description Permission granted to the current principal. */
            permission: components["schemas"]["Permission"];
            /** @description Effective global or asset-group scope for the permission. */
            scope: components["schemas"]["PermissionScope"];
        };
        /** @description Safe validation detail for one request field. */
        FieldError: {
            /** @description Stable machine-readable validation code. */
            code: string;
            /** @description Stable JSON field name or dotted field path. */
            field: string;
            /** @description Bounded operator-facing explanation. */
            message: string;
        };
        /**
         * @description Stable console permission identifiers.
         * @enum {string}
         */
        Permission: "agents.read" | "agents.revoke" | "findings.read" | "findings.triage" | "tokens.read" | "tokens.create" | "tokens.revoke" | "rules.read" | "rules.upload" | "audit.read" | "audit.export" | "audit.retention.manage" | "rbac.read" | "rbac.manage" | "asset_groups.manage" | "service_accounts.read" | "service_accounts.manage";
        /** @description Effective object scope attached to one permission. */
        PermissionScope: {
            /** @enum {string} */
            kind: "global";
        } | {
            /** @description Stable asset-group identifiers selected by the binding resolver. */
            asset_group_ids: string[];
            /** @enum {string} */
            kind: "asset_groups";
        };
        /** @description Stable RFC Problem Details-style error response used by the console API. */
        ProblemDetails: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Bounded request-field errors when validation can safely identify them. */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** @description Process-local correlation identifier. */
            request_id: string;
            /**
             * Format: int32
             * @description HTTP status code.
             */
            status: number;
            /** @description Short human-readable error title. */
            title: string;
        };
        /** @description Human principal represented by an authenticated browser session. */
        SessionPrincipal: {
            /** @description Operator-facing display label. */
            display_name: string;
            /** @description Stable local or federated user identifier. */
            id: string;
            /** @description Local username when the identity has one. */
            username?: string | null;
        };
        /** @description Successful response from `GET /api/v1/session` once C3 authentication is available. */
        SessionResponse: {
            /**
             * Format: date-time
             * @description RFC 3339 absolute session expiry instant.
             */
            absolute_expires_at: string;
            /** @description Assurance reached by the current session. */
            authentication_level: components["schemas"]["AuthenticationLevel"];
            /** @description Mechanism that established the session. */
            authentication_method: components["schemas"]["AuthenticationMethod"];
            /** @description Effective permissions and their scopes, resolved for this request. */
            capabilities: components["schemas"]["EffectiveCapability"][];
            /** @description Per-session value required in `X-CSRF-Token` on unsafe browser requests. */
            csrf_token: string;
            /**
             * Format: date-time
             * @description RFC 3339 instant when idle expiry occurs if the session is not used.
             */
            idle_expires_at: string;
            /** @description Current human principal. Service-account tokens cannot call this route. */
            principal: components["schemas"]["SessionPrincipal"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated browser session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Authentication is not implemented until C3 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
