/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agent_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agent_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticated_agent_certificates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the current authenticated browser session.
         * @description The C0 router deliberately returns a bounded failure instead of creating a
         *     temporary unauthenticated or implicitly privileged session.
         */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/v1/preauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preauth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Agent and current certificate metadata. */
        AgentDetail: components["schemas"]["AgentView"] & {
            /** @description Certificate metadata for the agent. */
            certificates: components["schemas"]["CertificateView"][];
        };
        /** @description A page of agents using the shared cursor response shape. */
        AgentPage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["AgentView"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /**
         * @description Lifecycle state reported for an enrolled agent.
         * @enum {string}
         */
        AgentStatus: "active" | "stale" | "revoked";
        /** @description Fleet counts visible to the current principal. */
        AgentSummary: {
            /**
             * Format: int64
             * @description Number of visible active agents.
             */
            active: number;
            /**
             * Format: int64
             * @description Number of visible revoked agents.
             */
            revoked: number;
            /**
             * Format: int64
             * @description Number of visible stale agents.
             */
            stale: number;
            /**
             * Format: int64
             * @description Number of visible enrolled agents.
             */
            total: number;
        };
        /** @description Operator-facing agent fields shared by the read API and seeded server. */
        AgentView: {
            /** @description Reported agent capabilities. */
            capabilities: string[];
            /** @description RFC 3339 enrollment time. */
            enrolled_at: string;
            /** @description Latest hostname reported by an authenticated heartbeat; this is an operator label. */
            hostname?: string | null;
            /** @description Stable platform agent identifier. */
            id: string;
            /** @description RFC 3339 time of the latest heartbeat, if present. */
            last_seen_at?: string | null;
            /** @description RFC 3339 revocation time, if revoked. */
            revoked_at?: string | null;
            /** @description Reported scanner version, if present. */
            scanner_version?: string | null;
            /** @description Current lifecycle state. */
            status: components["schemas"]["AgentStatus"];
        };
        /**
         * @description Authentication assurance reached by the current browser session.
         * @enum {string}
         */
        AuthenticationLevel: "single_factor" | "multi_factor";
        /**
         * @description Authentication mechanism that established a browser session.
         * @enum {string}
         */
        AuthenticationMethod: "local_password" | "oidc" | "saml";
        /** @description A page of certificate metadata using the shared cursor response shape. */
        CertificatePage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["CertificateView"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /** @description Certificate metadata exposed in an agent detail response. */
        CertificateView: {
            /** @description RFC 3339 certificate issuance time. */
            issued_at: string;
            /** @description RFC 3339 certificate expiry time. */
            not_after: string;
            /** @description RFC 3339 certificate validity start. */
            not_before: string;
            /** @description Certificate serial rendered as hexadecimal. */
            serial: string;
        };
        /** @description Validated cursor and limit accepted by cursor-paginated collection routes. */
        CursorPagination: {
            cursor?: string | null;
            /**
             * Format: int32
             * @default 50
             */
            limit: number;
        };
        /** @description One effective capability returned to the browser. */
        EffectiveCapability: {
            /** @description Permission granted to the current principal. */
            permission: components["schemas"]["Permission"];
            /** @description Effective global or asset-group scope for the permission. */
            scope: components["schemas"]["PermissionScope"];
        };
        /** @description Safe validation detail for one request field. */
        FieldError: {
            /** @description Stable machine-readable validation code. */
            code: string;
            /** @description Stable JSON field name or dotted field path. */
            field: string;
            /** @description Bounded operator-facing explanation. */
            message: string;
        };
        /** @description One historical observation event. */
        FindingHistoryEntry: {
            /** @description Agent associated with this event. */
            agent_id: string;
            /** @description Whether the observation was received through an authenticated agent. */
            authenticated: boolean;
            /**
             * Format: int32
             * @description Confidence as a percentage from 0 through 100.
             */
            confidence: number;
            /** @description Evidence key/value strings from the observation. */
            evidence: string[];
            /** @description Finding identifier from the partitioned event table. */
            id: string;
            /** @description Message recorded for this observation. */
            message: string;
            /** @description RFC 3339 time the agent or importer observed this finding. */
            observed_at: string;
            /** @description Observation provenance. */
            origin: components["schemas"]["FindingOrigin"];
            /** @description RFC 3339 time the platform received this observation. */
            received_at: string;
            /** @description Rule identifier within the rule set. */
            rule_id: string;
            /** @description Rule set that produced the event, or `~unknown` for legacy data. */
            rule_set_id: string;
            /**
             * Format: int64
             * @description Signed rule version.
             */
            rule_version: number;
            /** @description Scan that produced the observation. */
            scan_id: string;
            /** @description Severity recorded for this observation. */
            severity: components["schemas"]["Severity"];
        };
        /** @description A page of historical observation events using the shared cursor response shape. */
        FindingHistoryPage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["FindingHistoryEntry"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /**
         * @description Provenance of a stored observation.
         * @enum {string}
         */
        FindingOrigin: "online" | "import";
        /** @description A page of latest observations using the shared cursor response shape. */
        FindingPage: {
            /** @description RFC 3339 instant when this page was generated. */
            generated_at: string;
            /** @description Records in stable server-defined order. */
            items: components["schemas"]["FindingView"][];
            /** @description Opaque cursor for the next page, or `null` at the end. */
            next_cursor?: string | null;
        };
        /** @description Counts for the latest observation rows visible to the current principal. */
        FindingSummary: {
            /**
             * Format: int64
             * @description Visible critical latest observations.
             */
            critical: number;
            /**
             * Format: int64
             * @description Visible high latest observations.
             */
            high: number;
            /**
             * Format: int64
             * @description Number of visible agents with at least one latest observation.
             */
            impacted_agents: number;
            /**
             * Format: int64
             * @description Visible low latest observations.
             */
            low: number;
            /**
             * Format: int64
             * @description Visible medium latest observations.
             */
            medium: number;
            /**
             * Format: int64
             * @description Number of visible latest observation rows.
             */
            total: number;
        };
        /** @description Latest observation state for one agent, rule set, and rule. */
        FindingView: {
            /** @description Agent associated with this observation. */
            agent_id: string;
            /** @description Whether the observation was received through an authenticated agent. */
            authenticated: boolean;
            /**
             * Format: int32
             * @description Confidence as a percentage from 0 through 100.
             */
            confidence: number;
            /** @description Evidence key/value strings from the observation. */
            evidence: string[];
            /** @description RFC 3339 time of the first observation. */
            first_observed_at: string;
            /** @description Latest hostname reported by the agent; this is an operator label. */
            hostname?: string | null;
            /** @description Stable latest-finding identifier. */
            id: string;
            /** @description RFC 3339 time of the latest observation. */
            last_observed_at: string;
            /** @description Latest observation message. */
            message: string;
            /** @description Observation provenance. */
            origin: components["schemas"]["FindingOrigin"];
            /** @description RFC 3339 time the platform received this observation. */
            received_at: string;
            /** @description Rule identifier within the rule set. */
            rule_id: string;
            /** @description Rule set that produced the finding, or `~unknown` for legacy data. */
            rule_set_id: string;
            /**
             * Format: int64
             * @description Signed rule version.
             */
            rule_version: number;
            /** @description Scan that produced the observation. */
            scan_id: string;
            /** @description Latest observed severity. */
            severity: components["schemas"]["Severity"];
        };
        /** @description One-use local login request. The password is never echoed by the API. */
        LoginRequest: {
            /**
             * Format: password
             * @description Password supplied over the configured secure transport.
             */
            password: string;
            /** @description Canonical local username (case is normalized by the server). */
            username: string;
        };
        /** @description Acknowledgement returned after a local password login succeeds. */
        LoginResponse: {
            /** @description Always true for the successful response; the session cookie is set separately. */
            authenticated: boolean;
        };
        /**
         * @description Stable console permission identifiers.
         * @enum {string}
         */
        Permission: "agents.read" | "agents.revoke" | "findings.read" | "findings.triage" | "tokens.read" | "tokens.create" | "tokens.revoke" | "rules.read" | "rules.upload" | "audit.read" | "audit.export" | "audit.retention.manage" | "rbac.read" | "rbac.manage" | "asset_groups.manage" | "service_accounts.read" | "service_accounts.manage";
        /** @description Effective object scope attached to one permission. */
        PermissionScope: {
            /** @enum {string} */
            kind: "global";
        } | {
            /** @description Stable asset-group identifiers selected by the binding resolver. */
            asset_group_ids: string[];
            /** @enum {string} */
            kind: "asset_groups";
        };
        /** @description CSRF challenge returned before local password login. */
        PreauthResponse: {
            /** @description One-use value required in `X-CSRF-Token` on the login request. */
            csrf_token: string;
        };
        /** @description Stable RFC Problem Details-style error response used by the console API. */
        ProblemDetails: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Bounded request-field errors when validation can safely identify them. */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** @description Process-local correlation identifier. */
            request_id: string;
            /**
             * Format: int32
             * @description HTTP status code.
             */
            status: number;
            /** @description Short human-readable error title. */
            title: string;
        };
        /** @description Human principal represented by an authenticated browser session. */
        SessionPrincipal: {
            /** @description Operator-facing display label. */
            display_name: string;
            /** @description Stable local or federated user identifier. */
            id: string;
            /** @description Local username when the identity has one. */
            username?: string | null;
        };
        /** @description Successful response from `GET /api/v1/session` for an active session. */
        SessionResponse: {
            /**
             * Format: date-time
             * @description RFC 3339 absolute session expiry instant.
             */
            absolute_expires_at: string;
            /** @description Assurance reached by the current session. */
            authentication_level: components["schemas"]["AuthenticationLevel"];
            /** @description Mechanism that established the session. */
            authentication_method: components["schemas"]["AuthenticationMethod"];
            /** @description Effective permissions and their scopes, resolved for this request. */
            capabilities: components["schemas"]["EffectiveCapability"][];
            /** @description Per-session value required in `X-CSRF-Token` on unsafe browser requests. */
            csrf_token: string;
            /**
             * Format: date-time
             * @description RFC 3339 instant when idle expiry occurs if the session is not used.
             */
            idle_expires_at: string;
            /** @description Current human principal. Service-account tokens cannot call this route. */
            principal: components["schemas"]["SessionPrincipal"];
        };
        /**
         * @description Severity attached to the latest observation for a rule.
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authenticated_agents: {
        parameters: {
            query?: {
                /** @description active, stale, or revoked */
                state?: string;
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size from 1 to 100 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope-filtered agent page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_agent_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent counts visible to the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_agent_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible agent detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authenticated_agent_certificates: {
        parameters: {
            query?: {
                /** @description Opaque continuation cursor */
                cursor?: string;
                /** @description Page size from 1 to 100 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Stable agent identifier */
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible certificate metadata page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificatePage"];
                };
            };
            /** @description Invalid query or cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Read unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated browser session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Authentication is not implemented until C3 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured public origin */
                Origin: string;
                /** @description One-use token returned by pre-authentication */
                "X-CSRF-Token": string;
                /** @description Pre-auth and browser-binding cookies */
                Cookie: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; sets an opaque session cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Malformed authentication request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Generic invalid credentials response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Origin or CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication unavailable or busy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the configured public origin */
                Origin: string;
                /** @description Synchronizer token returned by the session route */
                "X-CSRF-Token": string;
                /** @description Opaque browser session cookie */
                Cookie: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Origin or CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    preauth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-use login challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreauthResponse"];
                };
            };
            /** @description Authentication unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
