//! Transactional local-console user, pre-authentication, and session storage.

use chrono::{DateTime, Duration, Utc};
use tokio_postgres::Row;

use crate::{Client, StoreError};

/// User credential data used for constant-shape password verification.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Credential {
    /// Stable local user id.
    pub user_id: String,
    /// Canonical local username.
    pub username: String,
    /// Operator-facing display name.
    pub display_name: String,
    /// Argon2id PHC string.
    pub password_phc: String,
    /// Whether the account can authenticate.
    pub enabled: bool,
    /// Generation captured when the session was created.
    pub auth_generation: i64,
}

/// Values required to provision one local account.
#[derive(Clone, Debug)]
pub struct NewLocalUser<'a> {
    /// User UUID.
    pub user_id: &'a str,
    /// Binding UUID.
    pub binding_id: &'a str,
    /// Canonical username.
    pub username: &'a str,
    /// Operator-facing display name.
    pub display_name: &'a str,
    /// Argon2id PHC string, never a plaintext password.
    pub password_phc: &'a str,
    /// Built-in role id (`viewer`, `analyst`, `operator`, or `admin`).
    pub role_id: &'a str,
    /// Actor identifier for audit.
    pub actor_id: &'a str,
    /// Provisioning time.
    pub now: DateTime<Utc>,
}

/// Hashes and times for one opaque browser session.
#[derive(Clone, Debug)]
pub struct NewSession<'a> {
    /// SHA-256 digest of the browser's random session token.
    pub session_sha256: &'a [u8],
    /// SHA-256 digest of its synchroniser CSRF value.
    pub csrf_sha256: &'a [u8],
    /// User UUID.
    pub user_id: &'a str,
    /// User authentication generation observed after password verification.
    pub auth_generation: i64,
    /// Creation time.
    pub now: DateTime<Utc>,
    /// Idle expiration.
    pub idle_expires_at: DateTime<Utc>,
    /// Absolute expiration.
    pub absolute_expires_at: DateTime<Utc>,
    /// Trusted request context included in the login audit event.
    pub audit: AuditContext<'a>,
}

/// Hashes and expiry for one one-use local pre-auth value.
#[derive(Clone, Debug)]
pub struct NewPreauth<'a> {
    /// SHA-256 digest of the random pre-auth cookie.
    pub token_sha256: &'a [u8],
    /// SHA-256 digest of the CSRF value.
    pub csrf_sha256: &'a [u8],
    /// SHA-256 digest binding the state to its initiating browser.
    pub browser_sha256: &'a [u8],
    /// Creation time.
    pub created_at: DateTime<Utc>,
    /// Expiry time.
    pub expires_at: DateTime<Utc>,
}

/// Redacted, trusted metadata for an authentication audit event.
#[derive(Clone, Copy, Debug, Default)]
pub struct AuditContext<'a> {
    /// Correlation id generated by the console request layer.
    pub request_id: Option<&'a str>,
    /// Source address from the socket or validated trusted proxy chain.
    pub source_address: Option<&'a str>,
    /// Bounded User-Agent header value.
    pub user_agent: Option<&'a str>,
}

/// Session data after validating account state, expiry, and auth generation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Session {
    /// User id.
    pub user_id: String,
    /// Canonical username.
    pub username: String,
    /// Operator-facing display name.
    pub display_name: String,
    /// SHA-256 digest of the CSRF value.
    pub csrf_sha256: Vec<u8>,
    /// Last successful activity.
    pub last_seen_at: DateTime<Utc>,
    /// Current idle expiry.
    pub idle_expires_at: DateTime<Utc>,
    /// Fixed absolute expiry.
    pub absolute_expires_at: DateTime<Utc>,
}

/// Active role binding for a local console user.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UserRoleBinding {
    /// Bound built-in role identifier.
    pub role_id: String,
    /// Asset group id for a scoped binding; `None` means global.
    pub asset_group_id: Option<String>,
}

/// Creates a user, credential, initial global role binding, and audit event
/// atomically. Password plaintext must already have been zeroized by caller.
pub async fn create_local_user(
    client: &mut Client,
    new_user: &NewLocalUser<'_>,
) -> Result<(), StoreError> {
    let tx = client.transaction().await?;
    tx.execute(
        "INSERT INTO console_users (user_id, username, display_name, created_at)
         VALUES ($1::text::uuid, $2, $3, $4)",
        &[
            &new_user.user_id,
            &new_user.username,
            &new_user.display_name,
            &new_user.now,
        ],
    )
    .await?;
    tx.execute(
        "INSERT INTO console_credentials (user_id, password_phc, changed_at)
         VALUES ($1::text::uuid, $2, $3)",
        &[&new_user.user_id, &new_user.password_phc, &new_user.now],
    )
    .await?;
    tx.execute(
        "INSERT INTO console_role_bindings
            (binding_id, user_id, role_id, created_at, created_by)
         VALUES ($1::text::uuid, $2::text::uuid, $3, $4, $5)",
        &[
            &new_user.binding_id,
            &new_user.user_id,
            &new_user.role_id,
            &new_user.now,
            &new_user.actor_id,
        ],
    )
    .await?;
    tx.execute(
        "INSERT INTO audit_log
            (actor, action, target, result, detail, actor_kind, actor_id,
             actor_display, target_kind, target_id)
         VALUES ($1, 'user.created', $2, 'success', jsonb_build_object('role_id', $3::text), 'local_admin', $1, $1,
                 'user', $2)",
        &[
            &new_user.actor_id,
            &new_user.username,
            &new_user.role_id,
        ],
    )
    .await?;
    tx.commit().await?;
    Ok(())
}

/// Looks up credential material by canonical username. Disabled accounts are
/// returned so callers can perform the same Argon2id work as other failures.
pub async fn credential_by_username(
    client: &Client,
    username: &str,
) -> Result<Option<Credential>, StoreError> {
    let row = client
        .query_opt(
            "SELECT u.user_id::text, u.username, u.display_name, c.password_phc,
                    u.enabled, u.auth_generation
             FROM console_users u JOIN console_credentials c USING (user_id)
             WHERE u.username = $1",
            &[&username],
        )
        .await?;
    Ok(row.as_ref().map(credential_from_row))
}

/// Returns the currently active role bindings for a user. The console resolves
/// these on every request so binding changes take effect immediately.
pub async fn user_role_bindings(
    client: &Client,
    user_id: &str,
) -> Result<Vec<UserRoleBinding>, StoreError> {
    let rows = client
        .query(
            "SELECT role_id, asset_group_id::text FROM console_role_bindings
             WHERE user_id = $1::text::uuid AND revoked_at IS NULL
             ORDER BY role_id, asset_group_id NULLS FIRST",
            &[&user_id],
        )
        .await?;
    Ok(rows
        .iter()
        .map(|row| UserRoleBinding {
            role_id: row.get(0),
            asset_group_id: row.get(1),
        })
        .collect())
}

/// Creates a session only if the enabled account still has the generation
/// whose password was just verified.
pub async fn create_session(
    client: &mut Client,
    session: &NewSession<'_>,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    tx.query_opt(
        "SELECT user_id FROM console_users
         WHERE user_id = $1::text::uuid AND enabled AND auth_generation = $2
         FOR SHARE",
        &[&session.user_id, &session.auth_generation],
    )
    .await?;
    let inserted = tx
        .execute(
            "INSERT INTO console_sessions
                (session_sha256, csrf_sha256, user_id, auth_generation, created_at,
                 last_seen_at, idle_expires_at, absolute_expires_at)
             SELECT $1, $2, u.user_id, u.auth_generation, $3, $3, $4, $5
             FROM console_users u
             WHERE u.user_id = $6::text::uuid AND u.enabled AND u.auth_generation = $7",
            &[
                &session.session_sha256,
                &session.csrf_sha256,
                &session.now,
                &session.idle_expires_at,
                &session.absolute_expires_at,
                &session.user_id,
                &session.auth_generation,
            ],
        )
        .await?;
    if inserted == 1 {
        let row = tx
            .query_one(
                "SELECT display_name FROM console_users WHERE user_id = $1::text::uuid",
                &[&session.user_id],
            )
            .await?;
        let display_name: String = row.get(0);
        append_auth_event(
            &tx,
            &session.audit,
            AuthAuditEvent {
                actor: session.user_id,
                action: "auth.login.succeeded",
                target: Some(session.user_id),
                result: "success",
                actor_kind: Some("user"),
                actor_id: Some(session.user_id),
                actor_display: Some(&display_name),
                authentication_method: Some("local_password"),
                target_kind: Some("user"),
                target_id: Some(session.user_id),
                reason_code: None,
            },
        )
        .await?;
    }
    tx.commit().await?;
    Ok(inserted == 1)
}

/// Loads only a live, unrevoked session whose account generation is current.
pub async fn session(
    client: &Client,
    session_sha256: &[u8],
    now: DateTime<Utc>,
) -> Result<Option<Session>, StoreError> {
    let row = client
        .query_opt(
            "SELECT u.user_id::text, u.username, u.display_name, s.csrf_sha256,
                    s.last_seen_at, s.idle_expires_at, s.absolute_expires_at
             FROM console_sessions s JOIN console_users u USING (user_id)
             WHERE s.session_sha256 = $1 AND s.revoked_at IS NULL
               AND s.idle_expires_at > $2 AND s.absolute_expires_at > $2
               AND u.enabled AND s.auth_generation = u.auth_generation",
            &[&session_sha256, &now],
        )
        .await?;
    Ok(row.as_ref().map(session_from_row))
}

/// Extends the idle expiry without ever extending the absolute lifetime.
pub async fn touch_session(
    client: &Client,
    session_sha256: &[u8],
    now: DateTime<Utc>,
    idle_lifetime: Duration,
) -> Result<bool, StoreError> {
    let idle_expires_at = now + idle_lifetime;
    let updated = client
        .execute(
            "UPDATE console_sessions s
             SET last_seen_at = $2,
                 idle_expires_at = LEAST(s.absolute_expires_at, $3)
             FROM console_users u
             WHERE s.session_sha256 = $1 AND u.user_id = s.user_id
               AND s.revoked_at IS NULL AND s.idle_expires_at > $2
               AND s.absolute_expires_at > $2 AND u.enabled
               AND s.auth_generation = u.auth_generation",
            &[&session_sha256, &now, &idle_expires_at],
        )
        .await?;
    Ok(updated == 1)
}

/// Revokes one session if it exists and has not already been revoked.
pub async fn revoke_session(
    client: &Client,
    session_sha256: &[u8],
    now: DateTime<Utc>,
) -> Result<bool, StoreError> {
    let updated = client
        .execute(
            "UPDATE console_sessions SET revoked_at = $2
             WHERE session_sha256 = $1 AND revoked_at IS NULL",
            &[&session_sha256, &now],
        )
        .await?;
    Ok(updated == 1)
}

/// Invalidates every existing session by advancing the account generation.
pub async fn revoke_user_sessions(
    client: &mut Client,
    user_id: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
    actor_id: &str,
    actor_kind: &str,
    reason_code: &str,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_users SET auth_generation = auth_generation + 1
             WHERE user_id = $1::text::uuid",
            &[&user_id],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    tx.execute(
        "UPDATE console_sessions SET revoked_at = COALESCE(revoked_at, $2)
         WHERE user_id = $1::text::uuid",
        &[&user_id, &now],
    )
    .await?;
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: actor_id,
            action: "auth.sessions.revoked",
            target: Some(user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: Some(reason_code),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Replaces an Argon2id credential and invalidates every session atomically.
pub async fn replace_password(
    client: &mut Client,
    user_id: &str,
    password_phc: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
    actor_id: &str,
    actor_kind: &str,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_credentials SET password_phc = $2, changed_at = $3, must_change = false
             WHERE user_id = $1::text::uuid",
            &[&user_id, &password_phc, &now],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    tx.execute(
        "UPDATE console_users SET auth_generation = auth_generation + 1
         WHERE user_id = $1::text::uuid",
        &[&user_id],
    )
    .await?;
    tx.execute(
        "UPDATE console_sessions SET revoked_at = COALESCE(revoked_at, $2)
         WHERE user_id = $1::text::uuid",
        &[&user_id, &now],
    )
    .await?;
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: actor_id,
            action: "auth.password.changed",
            target: Some(user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: None,
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Disables an enabled user and revokes all sessions in one audited transaction.
pub async fn disable_local_user(
    client: &mut Client,
    user_id: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
    actor_id: &str,
    actor_kind: &str,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_users SET enabled = false, disabled_at = $2,
                    auth_generation = auth_generation + 1
             WHERE user_id = $1::text::uuid AND enabled",
            &[&user_id, &now],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    tx.execute(
        "UPDATE console_sessions SET revoked_at = COALESCE(revoked_at, $2)
         WHERE user_id = $1::text::uuid",
        &[&user_id, &now],
    )
    .await?;
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: actor_id,
            action: "user.disabled",
            target: Some(user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: Some("administrator_disabled"),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Stores hash-only one-use local pre-authentication state.
pub async fn create_preauth(client: &Client, state: &NewPreauth<'_>) -> Result<(), StoreError> {
    client
        .execute(
            "INSERT INTO console_preauth
                (token_sha256, csrf_sha256, browser_sha256, created_at, expires_at)
             VALUES ($1, $2, $3, $4, $5)",
            &[
                &state.token_sha256,
                &state.csrf_sha256,
                &state.browser_sha256,
                &state.created_at,
                &state.expires_at,
            ],
        )
        .await?;
    Ok(())
}

/// Atomically consumes pre-authentication state only when all three digests
/// match and it has not expired or been used.
pub async fn consume_preauth(
    client: &Client,
    token_sha256: &[u8],
    csrf_sha256: &[u8],
    browser_sha256: &[u8],
    now: DateTime<Utc>,
) -> Result<bool, StoreError> {
    let updated = client
        .execute(
            "UPDATE console_preauth SET consumed_at = $4
             WHERE token_sha256 = $1 AND csrf_sha256 = $2 AND browser_sha256 = $3
               AND expires_at > $4 AND consumed_at IS NULL",
            &[&token_sha256, &csrf_sha256, &browser_sha256, &now],
        )
        .await?;
    Ok(updated == 1)
}

/// Reports whether any account/source throttle bucket is currently locked.
pub async fn login_is_throttled(
    client: &Client,
    bucket_sha256: &[&[u8]],
    now: DateTime<Utc>,
) -> Result<bool, StoreError> {
    let row = client
        .query_one(
            "SELECT EXISTS (
                SELECT 1 FROM console_auth_throttle
                WHERE bucket_sha256 = ANY($1) AND locked_until > $2
             )",
            &[&bucket_sha256, &now],
        )
        .await?;
    Ok(row.get(0))
}

/// Records one failed login in every supplied bucket. Window, limit, and lock
/// duration are policy inputs held by the console configuration.
pub async fn record_login_failure(
    client: &mut Client,
    bucket_sha256: &[&[u8]],
    now: DateTime<Utc>,
    window: Duration,
    failure_limit: i32,
    lock_for: Duration,
    audit: &AuditContext<'_>,
) -> Result<(), StoreError> {
    let tx = client.transaction().await?;
    let window_cutoff = now - window;
    let locked_until = now + lock_for;
    for bucket in bucket_sha256 {
        tx.execute(
            "INSERT INTO console_auth_throttle
                (bucket_sha256, window_started_at, failures, locked_until, updated_at)
             VALUES ($1, $2, 1, CASE WHEN $4 <= 1 THEN $5::timestamptz END, $2)
             ON CONFLICT (bucket_sha256) DO UPDATE SET
                window_started_at = CASE
                    WHEN console_auth_throttle.window_started_at <= $3
                    THEN $2 ELSE console_auth_throttle.window_started_at END,
                failures = CASE
                    WHEN console_auth_throttle.window_started_at <= $3
                    THEN 1 ELSE console_auth_throttle.failures + 1 END,
                locked_until = CASE
                    WHEN console_auth_throttle.window_started_at <= $3
                        THEN CASE WHEN $4 <= 1 THEN $5::timestamptz END
                    WHEN console_auth_throttle.failures + 1 >= $4
                        THEN GREATEST(COALESCE(console_auth_throttle.locked_until, $2),
                                      $5)
                    ELSE console_auth_throttle.locked_until END,
                updated_at = $2",
            &[&bucket, &now, &window_cutoff, &failure_limit, &locked_until],
        )
        .await?;
    }
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: "console-login",
            action: "auth.login.failed",
            target: None,
            result: "failure",
            actor_kind: Some("anonymous"),
            actor_id: None,
            actor_display: None,
            authentication_method: Some("local_password"),
            target_kind: None,
            target_id: None,
            reason_code: Some("invalid_credentials"),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(())
}

/// Clears successful login throttle buckets.
pub async fn clear_login_throttle(
    client: &Client,
    bucket_sha256: &[&[u8]],
    now: DateTime<Utc>,
) -> Result<(), StoreError> {
    client
        .execute(
            "UPDATE console_auth_throttle
             SET failures = 0, locked_until = NULL, window_started_at = $2, updated_at = $2
             WHERE bucket_sha256 = ANY($1)",
            &[&bucket_sha256, &now],
        )
        .await?;
    Ok(())
}

fn credential_from_row(row: &Row) -> Credential {
    Credential {
        user_id: row.get(0),
        username: row.get(1),
        display_name: row.get(2),
        password_phc: row.get(3),
        enabled: row.get(4),
        auth_generation: row.get(5),
    }
}

fn session_from_row(row: &Row) -> Session {
    Session {
        user_id: row.get(0),
        username: row.get(1),
        display_name: row.get(2),
        csrf_sha256: row.get(3),
        last_seen_at: row.get(4),
        idle_expires_at: row.get(5),
        absolute_expires_at: row.get(6),
    }
}

struct AuthAuditEvent<'a> {
    actor: &'a str,
    action: &'a str,
    target: Option<&'a str>,
    result: &'a str,
    actor_kind: Option<&'a str>,
    actor_id: Option<&'a str>,
    actor_display: Option<&'a str>,
    authentication_method: Option<&'a str>,
    target_kind: Option<&'a str>,
    target_id: Option<&'a str>,
    reason_code: Option<&'a str>,
}

async fn append_auth_event(
    tx: &tokio_postgres::Transaction<'_>,
    context: &AuditContext<'_>,
    event: AuthAuditEvent<'_>,
) -> Result<(), StoreError> {
    tx.execute(
        "INSERT INTO audit_log
            (actor, action, target, result, detail, request_id, actor_kind,
             actor_id, actor_display, authentication_method, target_kind,
             target_id, reason_code, source_address, user_agent)
         VALUES ($1, $2, $3, $4,
             CASE WHEN $12::text IS NULL THEN '{}'::jsonb
                  ELSE jsonb_build_object('reason_code', $12::text) END,
             $5, $6, $7, $8, $9, $10, $11, $12, $13::text::inet, $14)",
        &[
            &event.actor,
            &event.action,
            &event.target,
            &event.result,
            &context.request_id,
            &event.actor_kind,
            &event.actor_id,
            &event.actor_display,
            &event.authentication_method,
            &event.target_kind,
            &event.target_id,
            &event.reason_code,
            &context.source_address,
            &context.user_agent,
        ],
    )
    .await?;
    Ok(())
}
