//! Transactional local-console user, pre-authentication, and session storage.

use chrono::{DateTime, Duration, Utc};
use sha2::{Digest, Sha256};
use tokio_postgres::Row;

use crate::{Client, StoreError};

/// User credential data used for constant-shape password verification.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Credential {
    /// Stable local user id.
    pub user_id: String,
    /// Canonical local username.
    pub username: String,
    /// Operator-facing display name.
    pub display_name: String,
    /// Argon2id PHC string.
    pub password_phc: String,
    /// Whether the account can authenticate.
    pub enabled: bool,
    /// Generation captured when the session was created.
    pub auth_generation: i64,
}

/// Values required to provision one local account.
#[derive(Clone, Debug)]
pub struct NewLocalUser<'a> {
    /// User UUID.
    pub user_id: &'a str,
    /// Binding UUID.
    pub binding_id: &'a str,
    /// Canonical username.
    pub username: &'a str,
    /// Operator-facing display name.
    pub display_name: &'a str,
    /// Argon2id PHC string, never a plaintext password.
    pub password_phc: &'a str,
    /// Built-in role id (`viewer`, `analyst`, `operator`, or `admin`).
    pub role_id: &'a str,
    /// Actor identifier for audit.
    pub actor_id: &'a str,
    /// Provisioning time.
    pub now: DateTime<Utc>,
}

/// Hashes and times for one opaque browser session.
#[derive(Clone, Debug)]
pub struct NewSession<'a> {
    /// SHA-256 digest of the browser's random session token.
    pub session_sha256: &'a [u8],
    /// Existing browser session to revoke atomically when rotating after login.
    pub previous_session_sha256: Option<&'a [u8]>,
    /// SHA-256 digest of its synchroniser CSRF value.
    pub csrf_sha256: &'a [u8],
    /// User UUID.
    pub user_id: &'a str,
    /// User authentication generation observed after password verification.
    pub auth_generation: i64,
    /// Creation time.
    pub now: DateTime<Utc>,
    /// Idle expiration.
    pub idle_expires_at: DateTime<Utc>,
    /// Absolute expiration.
    pub absolute_expires_at: DateTime<Utc>,
    /// Trusted request context included in the login audit event.
    pub audit: AuditContext<'a>,
}

/// Hashes and expiry for one one-use local pre-auth value.
#[derive(Clone, Debug)]
pub struct NewPreauth<'a> {
    /// SHA-256 digest of the random pre-auth cookie.
    pub token_sha256: &'a [u8],
    /// SHA-256 digest of the CSRF value.
    pub csrf_sha256: &'a [u8],
    /// SHA-256 digest binding the state to its initiating browser.
    pub browser_sha256: &'a [u8],
    /// Creation time.
    pub created_at: DateTime<Utc>,
    /// Expiry time.
    pub expires_at: DateTime<Utc>,
}

/// Redacted, trusted metadata for an authentication audit event.
#[derive(Clone, Copy, Debug, Default)]
pub struct AuditContext<'a> {
    /// Correlation id generated by the console request layer.
    pub request_id: Option<&'a str>,
    /// Source address from the socket or validated trusted proxy chain.
    pub source_address: Option<&'a str>,
    /// Bounded User-Agent header value.
    pub user_agent: Option<&'a str>,
}

/// Session data after validating account state, expiry, and auth generation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Session {
    /// User id.
    pub user_id: String,
    /// Canonical username.
    pub username: String,
    /// Operator-facing display name.
    pub display_name: String,
    /// SHA-256 digest of the CSRF value.
    pub csrf_sha256: Vec<u8>,
    /// Last successful activity.
    pub last_seen_at: DateTime<Utc>,
    /// Current idle expiry.
    pub idle_expires_at: DateTime<Utc>,
    /// Fixed absolute expiry.
    pub absolute_expires_at: DateTime<Utc>,
}

/// Active role binding for a local console user.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UserRoleBinding {
    /// Bound built-in role identifier.
    pub role_id: String,
    /// Asset group id for a scoped binding; `None` means global.
    pub asset_group_id: Option<String>,
}

/// Non-secret local-user fields available to audited administrative listings.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LocalUserSummary {
    /// Stable user UUID.
    pub user_id: String,
    /// Canonical local username.
    pub username: String,
    /// Operator-facing label.
    pub display_name: String,
    /// Whether the account can authenticate.
    pub enabled: bool,
    /// Active built-in role bindings.
    pub role_ids: Vec<String>,
    /// Creation time.
    pub created_at: DateTime<Utc>,
    /// Most recent session activity, if any.
    pub last_seen_at: Option<DateTime<Utc>>,
}

/// A built-in or custom role and its permission identifiers.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RoleSummary {
    /// Stable role key.
    pub role_id: String,
    /// Display name.
    pub display_name: String,
    /// Whether the role is managed by the platform.
    pub builtin: bool,
    /// Permission identifiers granted by this role.
    pub permissions: Vec<String>,
}

/// Active user role binding with its resolved asset-group label.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BindingSummary {
    /// Stable binding UUID.
    pub binding_id: String,
    /// User id.
    pub user_id: String,
    /// Username.
    pub username: String,
    /// User display name.
    pub display_name: String,
    /// Bound role identifier.
    pub role_id: String,
    /// Asset group id; absent means global access.
    pub asset_group_id: Option<String>,
    /// Asset group label.
    pub asset_group_name: Option<String>,
    /// Creation instant.
    pub created_at: DateTime<Utc>,
    /// Actor who created the binding.
    pub created_by: String,
}

/// Manual asset group and its exact tag selectors.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AssetGroupSummary {
    /// Stable group UUID.
    pub asset_group_id: String,
    /// Operator-facing group name.
    pub name: String,
    /// Exact `key=value` selectors.
    pub selectors: Vec<String>,
}

/// Read-only access-control inventory for the administration page.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AccessInventory {
    /// Roles and permission identifiers.
    pub roles: Vec<RoleSummary>,
    /// Active local-user role bindings.
    pub bindings: Vec<BindingSummary>,
    /// Manual asset groups and selectors.
    pub asset_groups: Vec<AssetGroupSummary>,
    /// Enabled local users available for role assignment.
    pub users: Vec<LocalUserSummary>,
}

/// Saves an asset group and replaces its exact selector set with one audit row.
pub async fn save_asset_group(
    client: &mut Client,
    group_id: Option<&str>,
    name: &str,
    selectors: &[AgentTag],
    actor_id: &str,
    now: DateTime<Utc>,
) -> Result<Option<AssetGroupSummary>, StoreError> {
    let tx = client.transaction().await?;
    const TAG_LOCK: i64 = 0x7461_6773_6368_6765;
    tx.query_one("SELECT pg_advisory_xact_lock($1)", &[&TAG_LOCK])
        .await?;
    let row = if let Some(id) = group_id {
        tx.query_opt("UPDATE console_asset_groups SET name=$2 WHERE asset_group_id=$1::text::uuid RETURNING asset_group_id::text,name", &[&id,&name]).await?
    } else {
        tx.query_opt("INSERT INTO console_asset_groups(asset_group_id,name,created_at,created_by) VALUES(gen_random_uuid(),$1,$2,$3) RETURNING asset_group_id::text,name", &[&name,&now,&actor_id]).await?
    };
    let Some(row) = row else {
        tx.rollback().await?;
        return Ok(None);
    };
    let saved_id: String = row.get(0);
    let saved_name: String = row.get(1);
    tx.execute(
        "DELETE FROM console_asset_group_selectors WHERE asset_group_id=$1::text::uuid",
        &[&saved_id],
    )
    .await?;
    for selector in selectors {
        tx.execute("INSERT INTO console_asset_group_selectors(asset_group_id,tag_key,tag_value,created_at) VALUES($1::text::uuid,$2,$3,$4)", &[&saved_id,&selector.key,&selector.value,&now]).await?;
    }
    let selector_values = selectors
        .iter()
        .map(|selector| format!("{}={}", selector.key, selector.value))
        .collect::<Vec<_>>();
    let action = if group_id.is_some() {
        "asset_group.updated"
    } else {
        "asset_group.created"
    };
    tx.execute("INSERT INTO audit_log(actor,action,target,result,detail,actor_kind,actor_id,actor_display,target_kind,target_id) VALUES($1,$2,'asset_group','success',jsonb_build_object('name',$3::text,'selectors',to_jsonb($4::text[])),'user',$1,$1,'asset_group',$5)", &[&actor_id,&action,&saved_name,&selector_values,&saved_id]).await?;
    tx.commit().await?;
    Ok(Some(AssetGroupSummary {
        asset_group_id: saved_id,
        name: saved_name,
        selectors: selectors
            .iter()
            .map(|s| format!("{}={}", s.key, s.value))
            .collect(),
    }))
}

/// One exact agent tag (`key=value`).
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AgentTag {
    /// Tag key.
    pub key: String,
    /// Tag value.
    pub value: String,
}

/// Tag-set preview with groups whose membership changes.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AgentTagPreview {
    /// Existing exact tags.
    pub current: Vec<AgentTag>,
    /// Proposed exact tags.
    pub proposed: Vec<AgentTag>,
    /// Groups the agent would enter.
    pub gained_groups: Vec<(String, String)>,
    /// Groups the agent would leave.
    pub lost_groups: Vec<(String, String)>,
    /// Scoped role bindings gained through the new group membership.
    pub gained_bindings: Vec<TagBindingImpact>,
    /// Scoped role bindings lost with the old group membership.
    pub lost_bindings: Vec<TagBindingImpact>,
    /// Opaque token bound to this snapshot and proposal.
    pub token: String,
}

/// Safe details for an active scoped role binding affected by a tag change.
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize)]
pub struct TagBindingImpact {
    /// Binding UUID.
    pub binding_id: String,
    /// Username.
    pub username: String,
    /// Role identifier.
    pub role_id: String,
    /// Asset group name.
    pub asset_group_name: String,
}

/// Previews exact-tag membership changes without modifying the database.
pub async fn preview_agent_tags(
    client: &Client,
    agent_id: &str,
    proposed: &[AgentTag],
) -> Result<Option<AgentTagPreview>, StoreError> {
    let exists = client
        .query_opt("SELECT 1 FROM agents WHERE agent_id=$1", &[&agent_id])
        .await?;
    if exists.is_none() {
        return Ok(None);
    }
    let current = client
        .query(
            "SELECT tag_key,tag_value FROM console_agent_tags WHERE agent_id=$1 ORDER BY tag_key",
            &[&agent_id],
        )
        .await?
        .into_iter()
        .map(|r| AgentTag {
            key: r.get(0),
            value: r.get(1),
        })
        .collect::<Vec<_>>();
    let groups = tag_group_membership(client, &current, proposed).await?;
    let gained_bindings = tag_binding_impacts(client, &groups.0).await?;
    let lost_bindings = tag_binding_impacts(client, &groups.1).await?;
    let mut hash = Sha256::new();
    hash.update(
        serde_json::to_vec(&(
            agent_id,
            &current,
            proposed,
            &groups.0,
            &groups.1,
            &gained_bindings,
            &lost_bindings,
        ))
        .unwrap_or_default(),
    );
    Ok(Some(AgentTagPreview {
        current,
        proposed: proposed.to_vec(),
        gained_groups: groups.0,
        lost_groups: groups.1,
        gained_bindings,
        lost_bindings,
        token: encode_hex(&hash.finalize()),
    }))
}

/// Applies an unchanged preview, replacing tags and recording membership impact atomically.
pub async fn apply_agent_tags(
    client: &mut Client,
    agent_id: &str,
    proposed: &[AgentTag],
    preview_token: &str,
    actor_id: &str,
    now: DateTime<Utc>,
) -> Result<Option<AgentTagPreview>, StoreError> {
    let tx = client.transaction().await?;
    const TAG_LOCK: i64 = 0x7461_6773_6368_6765;
    tx.query_one("SELECT pg_advisory_xact_lock($1)", &[&TAG_LOCK])
        .await?;
    tx.query_opt(
        "SELECT agent_id FROM agents WHERE agent_id=$1 FOR UPDATE",
        &[&agent_id],
    )
    .await?;
    let exists = tx
        .query_opt("SELECT 1 FROM agents WHERE agent_id=$1", &[&agent_id])
        .await?;
    if exists.is_none() {
        tx.rollback().await?;
        return Ok(None);
    }
    let current = tx
        .query(
            "SELECT tag_key,tag_value FROM console_agent_tags WHERE agent_id=$1 ORDER BY tag_key",
            &[&agent_id],
        )
        .await?
        .into_iter()
        .map(|r| AgentTag {
            key: r.get(0),
            value: r.get(1),
        })
        .collect::<Vec<_>>();
    let groups = tag_group_membership(&tx, &current, proposed).await?;
    let gained_bindings = tag_binding_impacts(&tx, &groups.0).await?;
    let lost_bindings = tag_binding_impacts(&tx, &groups.1).await?;
    let mut hash = Sha256::new();
    hash.update(
        serde_json::to_vec(&(
            agent_id,
            &current,
            proposed,
            &groups.0,
            &groups.1,
            &gained_bindings,
            &lost_bindings,
        ))
        .unwrap_or_default(),
    );
    let token = encode_hex(&hash.finalize());
    if token != preview_token {
        tx.rollback().await?;
        return Ok(Some(AgentTagPreview {
            current,
            proposed: proposed.to_vec(),
            gained_groups: groups.0,
            lost_groups: groups.1,
            gained_bindings,
            lost_bindings,
            token,
        }));
    }
    tx.execute(
        "DELETE FROM console_agent_tags WHERE agent_id=$1",
        &[&agent_id],
    )
    .await?;
    for tag in proposed {
        tx.execute("INSERT INTO console_agent_tags(agent_id,tag_key,tag_value,changed_at,changed_by) VALUES($1,$2,$3,$4,$5)", &[&agent_id,&tag.key,&tag.value,&now,&actor_id]).await?;
    }
    let current_values = current
        .iter()
        .map(|tag| format!("{}={}", tag.key, tag.value))
        .collect::<Vec<_>>();
    let proposed_values = proposed
        .iter()
        .map(|tag| format!("{}={}", tag.key, tag.value))
        .collect::<Vec<_>>();
    let gained_groups = groups
        .0
        .iter()
        .map(|group| format!("{}={}", group.0, group.1))
        .collect::<Vec<_>>();
    let lost_groups = groups
        .1
        .iter()
        .map(|group| format!("{}={}", group.0, group.1))
        .collect::<Vec<_>>();
    let binding_summary = |bindings: &[TagBindingImpact]| {
        bindings
            .iter()
            .map(|binding| {
                format!(
                    "{}:{}:{}:{}",
                    binding.binding_id, binding.username, binding.role_id, binding.asset_group_name
                )
            })
            .collect::<Vec<_>>()
    };
    let gained_bindings = binding_summary(&gained_bindings);
    let lost_bindings = binding_summary(&lost_bindings);
    tx.execute("INSERT INTO audit_log(actor,action,target,result,detail,actor_kind,actor_id,actor_display,target_kind,target_id) VALUES($1,'agent.tags.changed','agent','success',jsonb_build_object('current_tags',to_jsonb($2::text[]),'proposed_tags',to_jsonb($3::text[]),'gained_groups',to_jsonb($4::text[]),'lost_groups',to_jsonb($5::text[]),'gained_bindings',to_jsonb($6::text[]),'lost_bindings',to_jsonb($7::text[])),'user',$1,$1,'agent',$8)", &[&actor_id,&current_values,&proposed_values,&gained_groups,&lost_groups,&gained_bindings,&lost_bindings,&agent_id]).await?;
    tx.commit().await?;
    Ok(None)
}

async fn tag_group_membership<C: deadpool_postgres::GenericClient + Sync>(
    client: &C,
    current: &[AgentTag],
    proposed: &[AgentTag],
) -> Result<(Vec<(String, String)>, Vec<(String, String)>), StoreError> {
    let rows = client.query("SELECT g.asset_group_id::text,g.name,COALESCE(array_agg(s.tag_key||'='||s.tag_value ORDER BY s.tag_key) FILTER(WHERE s.tag_key IS NOT NULL),ARRAY[]::text[]) FROM console_asset_groups g LEFT JOIN console_asset_group_selectors s USING(asset_group_id) GROUP BY g.asset_group_id ORDER BY g.name", &[]).await?;
    let matches = |selectors: &Vec<String>, tags: &[AgentTag]| {
        selectors.iter().all(|selector| {
            tags.iter()
                .any(|tag| selector == &format!("{}={}", tag.key, tag.value))
        })
    };
    let now = rows
        .iter()
        .filter(|r| matches(&r.get::<_, Vec<String>>(2), current))
        .map(|r| (r.get(0), r.get(1)))
        .collect::<Vec<_>>();
    let next = rows
        .iter()
        .filter(|r| matches(&r.get::<_, Vec<String>>(2), proposed))
        .map(|r| (r.get(0), r.get(1)))
        .collect::<Vec<_>>();
    Ok((
        next.iter().filter(|g| !now.contains(g)).cloned().collect(),
        now.iter().filter(|g| !next.contains(g)).cloned().collect(),
    ))
}

async fn tag_binding_impacts<C: deadpool_postgres::GenericClient + Sync>(
    client: &C,
    groups: &[(String, String)],
) -> Result<Vec<TagBindingImpact>, StoreError> {
    if groups.is_empty() {
        return Ok(Vec::new());
    }
    let ids = groups
        .iter()
        .map(|group| group.0.clone())
        .collect::<Vec<_>>();
    let rows = client.query(
        "SELECT b.binding_id::text,u.username,b.role_id,g.name FROM console_role_bindings b JOIN console_users u USING(user_id) JOIN console_asset_groups g USING(asset_group_id) WHERE b.revoked_at IS NULL AND u.enabled AND b.asset_group_id::text=ANY($1::text[]) ORDER BY g.name,u.username,b.role_id,b.binding_id LIMIT 501",
        &[&ids],
    ).await?;
    if rows.len() > 500 {
        return Err(StoreError::Query);
    }
    Ok(rows
        .into_iter()
        .map(|row| TagBindingImpact {
            binding_id: row.get(0),
            username: row.get(1),
            role_id: row.get(2),
            asset_group_name: row.get(3),
        })
        .collect())
}

fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 15) as usize] as char);
    }
    out
}

/// Outcome of revoking an active local-user role binding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BindingRevocation {
    /// Binding was revoked and audited.
    Revoked,
    /// Binding did not exist or was already revoked.
    NotFound,
    /// This is the final global Admin binding and cannot be revoked.
    LastGlobalAdmin,
}

/// Lists the current roles, active user bindings, and asset group selectors.
pub async fn access_inventory(client: &Client) -> Result<AccessInventory, StoreError> {
    let role_rows = client
        .query(
            "SELECT r.role_id, r.display_name, r.builtin,
                COALESCE(array_agg(rp.permission_id ORDER BY rp.permission_id)
                    FILTER (WHERE rp.permission_id IS NOT NULL), ARRAY[]::text[])
         FROM console_roles r LEFT JOIN console_role_permissions rp USING (role_id)
         GROUP BY r.role_id ORDER BY r.role_id",
            &[],
        )
        .await?;
    let binding_rows = client
        .query(
            "SELECT b.binding_id::text, u.user_id::text, u.username, u.display_name,
                b.role_id, b.asset_group_id::text, g.name, b.created_at, b.created_by
         FROM console_role_bindings b JOIN console_users u USING (user_id)
         LEFT JOIN console_asset_groups g USING (asset_group_id)
         WHERE b.user_id IS NOT NULL AND b.revoked_at IS NULL
         ORDER BY u.username, b.role_id, g.name NULLS FIRST, b.binding_id",
            &[],
        )
        .await?;
    let group_rows = client.query(
        "SELECT g.asset_group_id::text, g.name,
                COALESCE(array_agg(s.tag_key || '=' || s.tag_value ORDER BY s.tag_key)
                    FILTER (WHERE s.tag_key IS NOT NULL), ARRAY[]::text[])
         FROM console_asset_groups g LEFT JOIN console_asset_group_selectors s USING (asset_group_id)
         GROUP BY g.asset_group_id ORDER BY g.name", &[],
    ).await?;
    let users = list_local_users(client)
        .await?
        .into_iter()
        .filter(|user| user.enabled)
        .collect();
    Ok(AccessInventory {
        roles: role_rows
            .iter()
            .map(|row| RoleSummary {
                role_id: row.get(0),
                display_name: row.get(1),
                builtin: row.get(2),
                permissions: row.get(3),
            })
            .collect(),
        bindings: binding_rows
            .iter()
            .map(|row| BindingSummary {
                binding_id: row.get(0),
                user_id: row.get(1),
                username: row.get(2),
                display_name: row.get(3),
                role_id: row.get(4),
                asset_group_id: row.get(5),
                asset_group_name: row.get(6),
                created_at: row.get(7),
                created_by: row.get(8),
            })
            .collect(),
        asset_groups: group_rows
            .iter()
            .map(|row| AssetGroupSummary {
                asset_group_id: row.get(0),
                name: row.get(1),
                selectors: row.get(2),
            })
            .collect(),
        users,
    })
}

/// Creates a local-user role binding and its audit row atomically. Returns
/// `None` when the user, role, group, or unique active binding is unavailable.
pub async fn create_user_role_binding(
    client: &mut Client,
    user_id: &str,
    role_id: &str,
    asset_group_id: Option<&str>,
    actor_id: &str,
    now: DateTime<Utc>,
) -> Result<Option<BindingSummary>, StoreError> {
    let tx = client.transaction().await?;
    let row = tx.query_opt(
        "INSERT INTO console_role_bindings
             (binding_id, user_id, role_id, asset_group_id, created_at, created_by)
         SELECT gen_random_uuid(), u.user_id, r.role_id, g.asset_group_id, $4, $5
         FROM console_users u CROSS JOIN console_roles r
         LEFT JOIN console_asset_groups g ON g.asset_group_id::text = $3
         WHERE u.user_id::text = $1 AND u.enabled AND r.role_id = $2
           AND (($3::text IS NULL AND g.asset_group_id IS NULL) OR g.asset_group_id IS NOT NULL)
         ON CONFLICT DO NOTHING
         RETURNING binding_id::text, user_id::text, role_id, asset_group_id::text, created_at, created_by",
        &[&user_id, &role_id, &asset_group_id, &now, &actor_id],
    ).await?;
    let Some(row) = row else {
        tx.rollback().await?;
        return Ok(None);
    };
    let group_id: Option<String> = row.get(3);
    let group_name: Option<String> = if let Some(id) = group_id.as_deref() {
        tx.query_opt(
            "SELECT name FROM console_asset_groups WHERE asset_group_id::text = $1",
            &[&id],
        )
        .await?
        .map(|row| row.get(0))
    } else {
        None
    };
    let binding = tx
        .query_one(
            "SELECT $1::text, u.user_id::text, u.username, u.display_name, $2::text,
                $3::text, $4::text, $5::timestamptz, $6::text
         FROM console_users u WHERE u.user_id = $7::text::uuid",
            &[
                &row.get::<_, String>(0),
                &row.get::<_, String>(2),
                &group_id,
                &group_name,
                &row.get::<_, DateTime<Utc>>(4),
                &row.get::<_, String>(5),
                &user_id,
            ],
        )
        .await?;
    tx.execute(
        "INSERT INTO audit_log (actor, action, target, result, detail, actor_kind, actor_id,
             actor_display, target_kind, target_id)
         VALUES ($1, 'rbac.binding.created', 'role_binding', 'success',
             jsonb_build_object('role_id', $2::text, 'asset_group_id', $3::text),
             'user', $1, $1, 'role_binding', $4::text)",
        &[
            &actor_id,
            &role_id,
            &asset_group_id,
            &row.get::<_, String>(0),
        ],
    )
    .await?;
    let result = BindingSummary {
        binding_id: binding.get(0),
        user_id: binding.get(1),
        username: binding.get(2),
        display_name: binding.get(3),
        role_id: binding.get(4),
        asset_group_id: binding.get(5),
        asset_group_name: binding.get(6),
        created_at: binding.get(7),
        created_by: binding.get(8),
    };
    tx.commit().await?;
    Ok(Some(result))
}

/// Revokes one active local-user role binding and audits the change atomically.
pub async fn revoke_user_role_binding(
    client: &mut Client,
    binding_id: &str,
    actor_id: &str,
    now: DateTime<Utc>,
) -> Result<BindingRevocation, StoreError> {
    let tx = client.transaction().await?;
    const ACCESS_BINDING_LOCK: i64 = 0x6f76_6962_6573;
    tx.query_one("SELECT pg_advisory_xact_lock($1)", &[&ACCESS_BINDING_LOCK])
        .await?;
    let row = tx
        .query_opt(
            "SELECT b.role_id, b.asset_group_id::text, u.enabled
             FROM console_role_bindings b JOIN console_users u USING (user_id)
             WHERE b.binding_id = $1::text::uuid AND b.user_id IS NOT NULL AND b.revoked_at IS NULL
             FOR UPDATE",
            &[&binding_id],
        )
        .await?;
    let Some(row) = row else {
        tx.rollback().await?;
        return Ok(BindingRevocation::NotFound);
    };
    let role_id: String = row.get(0);
    let group_id: Option<String> = row.get(1);
    let target_enabled: bool = row.get(2);
    if role_id == "admin" && group_id.is_none() && target_enabled {
        let global_admins: i64 = tx
            .query_one(
                "SELECT count(*) FROM console_role_bindings b
                 JOIN console_users u USING (user_id)
                 WHERE u.enabled AND b.role_id = 'admin' AND b.asset_group_id IS NULL
                   AND b.revoked_at IS NULL",
                &[],
            )
            .await?
            .get(0);
        if global_admins <= 1 {
            tx.rollback().await?;
            return Ok(BindingRevocation::LastGlobalAdmin);
        }
    }
    tx.execute(
        "UPDATE console_role_bindings SET revoked_at = $2, revoked_by = $3
         WHERE binding_id = $1::text::uuid",
        &[&binding_id, &now, &actor_id],
    )
    .await?;
    tx.execute(
        "INSERT INTO audit_log (actor, action, target, result, detail, actor_kind, actor_id,
             actor_display, target_kind, target_id)
         VALUES ($1, 'rbac.binding.revoked', 'role_binding', 'success',
             jsonb_build_object('role_id', $2::text, 'asset_group_id', $3::text),
             'user', $1, $1, 'role_binding', $4::text)",
        &[&actor_id, &role_id, &group_id, &binding_id],
    )
    .await?;
    tx.commit().await?;
    Ok(BindingRevocation::Revoked)
}

/// Lists local users without credentials, session secrets, or throttle hashes.
pub async fn list_local_users(client: &Client) -> Result<Vec<LocalUserSummary>, StoreError> {
    let rows = client
        .query(
            "SELECT u.user_id::text, u.username, u.display_name, u.enabled, u.created_at,
                    array_agg(DISTINCT b.role_id ORDER BY b.role_id)
                        FILTER (WHERE b.role_id IS NOT NULL),
                    max(s.last_seen_at)
             FROM console_users u
             LEFT JOIN console_role_bindings b
               ON b.user_id = u.user_id AND b.revoked_at IS NULL
             LEFT JOIN console_sessions s ON s.user_id = u.user_id
             GROUP BY u.user_id
             ORDER BY u.username",
            &[],
        )
        .await?;
    Ok(rows
        .iter()
        .map(|row| LocalUserSummary {
            user_id: row.get(0),
            username: row.get(1),
            display_name: row.get(2),
            enabled: row.get(3),
            created_at: row.get(4),
            role_ids: row.get::<_, Option<Vec<String>>>(5).unwrap_or_default(),
            last_seen_at: row.get(6),
        })
        .collect())
}

/// Clears an active per-account login lock and records the recovery atomically.
pub async fn unlock_local_user(
    client: &mut Client,
    username: &str,
    now: DateTime<Utc>,
    actor_id: &str,
    actor_kind: &str,
) -> Result<bool, StoreError> {
    let account_bucket = account_throttle_bucket(username);
    let tx = client.transaction().await?;
    let user_id: Option<String> = tx
        .query_opt(
            "SELECT user_id::text FROM console_users WHERE username = $1 AND enabled FOR UPDATE",
            &[&username],
        )
        .await?
        .map(|row| row.get(0));
    let Some(user_id) = user_id else {
        tx.rollback().await?;
        return Ok(false);
    };
    let cleared = tx
        .execute(
            "DELETE FROM console_auth_throttle WHERE bucket_sha256 = $1 AND locked_until > $2",
            &[&&account_bucket[..], &now],
        )
        .await?;
    if cleared == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    append_auth_event(
        &tx,
        &AuditContext::default(),
        AuthAuditEvent {
            actor: actor_id,
            action: "user.unlocked",
            target: Some(&user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(&user_id),
            reason_code: Some("administrator_unlock"),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Derives the same account bucket used by local browser login throttling.
fn account_throttle_bucket(username: &str) -> [u8; 32] {
    let mut hash = Sha256::new();
    hash.update(b"openvibes-console-login-throttle-v1\0account\0");
    hash.update(username.as_bytes());
    hash.finalize().into()
}

/// Creates a user, credential, initial global role binding, and audit event
/// atomically. Password plaintext must already have been zeroized by caller.
pub async fn create_local_user(
    client: &mut Client,
    new_user: &NewLocalUser<'_>,
) -> Result<(), StoreError> {
    let tx = client.transaction().await?;
    tx.execute(
        "INSERT INTO console_users (user_id, username, display_name, created_at)
         VALUES ($1::text::uuid, $2, $3, $4)",
        &[
            &new_user.user_id,
            &new_user.username,
            &new_user.display_name,
            &new_user.now,
        ],
    )
    .await?;
    tx.execute(
        "INSERT INTO console_credentials (user_id, password_phc, changed_at)
         VALUES ($1::text::uuid, $2, $3)",
        &[&new_user.user_id, &new_user.password_phc, &new_user.now],
    )
    .await?;
    tx.execute(
        "INSERT INTO console_role_bindings
            (binding_id, user_id, role_id, created_at, created_by)
         VALUES ($1::text::uuid, $2::text::uuid, $3, $4, $5)",
        &[
            &new_user.binding_id,
            &new_user.user_id,
            &new_user.role_id,
            &new_user.now,
            &new_user.actor_id,
        ],
    )
    .await?;
    tx.execute(
        "INSERT INTO audit_log
            (actor, action, target, result, detail, actor_kind, actor_id,
             actor_display, target_kind, target_id)
         VALUES ($1, 'user.created', $2, 'success', jsonb_build_object('role_id', $3::text), 'local_admin', $1, $1,
                 'user', $2)",
        &[
            &new_user.actor_id,
            &new_user.username,
            &new_user.role_id,
        ],
    )
    .await?;
    tx.commit().await?;
    Ok(())
}

/// Looks up credential material by canonical username. Disabled accounts are
/// returned so callers can perform the same Argon2id work as other failures.
pub async fn credential_by_username(
    client: &Client,
    username: &str,
) -> Result<Option<Credential>, StoreError> {
    let row = client
        .query_opt(
            "SELECT u.user_id::text, u.username, u.display_name, c.password_phc,
                    u.enabled, u.auth_generation
             FROM console_users u JOIN console_credentials c USING (user_id)
             WHERE u.username = $1",
            &[&username],
        )
        .await?;
    Ok(row.as_ref().map(credential_from_row))
}

/// Returns the currently active role bindings for a user. The console resolves
/// these on every request so binding changes take effect immediately.
pub async fn user_role_bindings(
    client: &Client,
    user_id: &str,
) -> Result<Vec<UserRoleBinding>, StoreError> {
    let rows = client
        .query(
            "SELECT role_id, asset_group_id::text FROM console_role_bindings
             WHERE user_id = $1::text::uuid AND revoked_at IS NULL
             ORDER BY role_id, asset_group_id NULLS FIRST",
            &[&user_id],
        )
        .await?;
    Ok(rows
        .iter()
        .map(|row| UserRoleBinding {
            role_id: row.get(0),
            asset_group_id: row.get(1),
        })
        .collect())
}

/// Creates a session only if the enabled account still has the generation
/// whose password was just verified.
pub async fn create_session(
    client: &mut Client,
    session: &NewSession<'_>,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    tx.query_opt(
        "SELECT user_id FROM console_users
         WHERE user_id = $1::text::uuid AND enabled AND auth_generation = $2
         FOR SHARE",
        &[&session.user_id, &session.auth_generation],
    )
    .await?;
    let inserted = tx
        .execute(
            "INSERT INTO console_sessions
                (session_sha256, csrf_sha256, user_id, auth_generation, created_at,
                 last_seen_at, idle_expires_at, absolute_expires_at)
             SELECT $1, $2, u.user_id, u.auth_generation, $3, $3, $4, $5
             FROM console_users u
             WHERE u.user_id = $6::text::uuid AND u.enabled AND u.auth_generation = $7",
            &[
                &session.session_sha256,
                &session.csrf_sha256,
                &session.now,
                &session.idle_expires_at,
                &session.absolute_expires_at,
                &session.user_id,
                &session.auth_generation,
            ],
        )
        .await?;
    if inserted == 1 {
        if let Some(previous_session_sha256) = session.previous_session_sha256 {
            tx.execute(
                "UPDATE console_sessions SET revoked_at = $2
                 WHERE session_sha256 = $1 AND revoked_at IS NULL",
                &[&previous_session_sha256, &session.now],
            )
            .await?;
        }
        let row = tx
            .query_one(
                "SELECT display_name FROM console_users WHERE user_id = $1::text::uuid",
                &[&session.user_id],
            )
            .await?;
        let display_name: String = row.get(0);
        append_auth_event(
            &tx,
            &session.audit,
            AuthAuditEvent {
                actor: session.user_id,
                action: "auth.login.succeeded",
                target: Some(session.user_id),
                result: "success",
                actor_kind: Some("user"),
                actor_id: Some(session.user_id),
                actor_display: Some(&display_name),
                authentication_method: Some("local_password"),
                target_kind: Some("user"),
                target_id: Some(session.user_id),
                reason_code: None,
            },
        )
        .await?;
    }
    tx.commit().await?;
    Ok(inserted == 1)
}

/// Loads only a live, unrevoked session whose account generation is current.
pub async fn session(
    client: &Client,
    session_sha256: &[u8],
    now: DateTime<Utc>,
) -> Result<Option<Session>, StoreError> {
    let row = client
        .query_opt(
            "SELECT u.user_id::text, u.username, u.display_name, s.csrf_sha256,
                    s.last_seen_at, s.idle_expires_at, s.absolute_expires_at
             FROM console_sessions s JOIN console_users u USING (user_id)
             WHERE s.session_sha256 = $1 AND s.revoked_at IS NULL
               AND s.idle_expires_at > $2 AND s.absolute_expires_at > $2
               AND u.enabled AND s.auth_generation = u.auth_generation",
            &[&session_sha256, &now],
        )
        .await?;
    Ok(row.as_ref().map(session_from_row))
}

/// Extends the idle expiry without ever extending the absolute lifetime.
pub async fn touch_session(
    client: &Client,
    session_sha256: &[u8],
    now: DateTime<Utc>,
    idle_lifetime: Duration,
) -> Result<bool, StoreError> {
    let idle_expires_at = now + idle_lifetime;
    let updated = client
        .execute(
            "UPDATE console_sessions s
             SET last_seen_at = $2,
                 idle_expires_at = LEAST(s.absolute_expires_at, $3)
             FROM console_users u
             WHERE s.session_sha256 = $1 AND u.user_id = s.user_id
               AND s.revoked_at IS NULL AND s.idle_expires_at > $2
               AND s.absolute_expires_at > $2 AND u.enabled
               AND s.auth_generation = u.auth_generation",
            &[&session_sha256, &now, &idle_expires_at],
        )
        .await?;
    Ok(updated == 1)
}

/// Revokes one session if it exists and has not already been revoked.
pub async fn revoke_session(
    client: &mut Client,
    session_sha256: &[u8],
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let row = tx
        .query_opt(
            "UPDATE console_sessions SET revoked_at = $2
             WHERE session_sha256 = $1 AND revoked_at IS NULL
             RETURNING user_id::text",
            &[&session_sha256, &now],
        )
        .await?;
    let Some(row) = row else {
        tx.rollback().await?;
        return Ok(false);
    };
    let user_id: String = row.get(0);
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: &user_id,
            action: "auth.logout.succeeded",
            target: Some(&user_id),
            result: "success",
            actor_kind: Some("user"),
            actor_id: Some(&user_id),
            actor_display: None,
            authentication_method: Some("local_password"),
            target_kind: Some("user"),
            target_id: Some(&user_id),
            reason_code: None,
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Invalidates every existing session by advancing the account generation.
pub async fn revoke_user_sessions(
    client: &mut Client,
    user_id: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
    actor_id: &str,
    actor_kind: &str,
    reason_code: &str,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_users SET auth_generation = auth_generation + 1
             WHERE user_id = $1::text::uuid",
            &[&user_id],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    tx.execute(
        "UPDATE console_sessions SET revoked_at = COALESCE(revoked_at, $2)
         WHERE user_id = $1::text::uuid",
        &[&user_id, &now],
    )
    .await?;
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: actor_id,
            action: "auth.sessions.revoked",
            target: Some(user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: Some(reason_code),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Replaces an Argon2id credential and invalidates every session atomically.
pub async fn replace_password(
    client: &mut Client,
    user_id: &str,
    password_phc: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
    actor_id: &str,
    actor_kind: &str,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_credentials SET password_phc = $2, changed_at = $3, must_change = false
             WHERE user_id = $1::text::uuid",
            &[&user_id, &password_phc, &now],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    tx.execute(
        "UPDATE console_users SET auth_generation = auth_generation + 1
         WHERE user_id = $1::text::uuid",
        &[&user_id],
    )
    .await?;
    tx.execute(
        "UPDATE console_sessions SET revoked_at = COALESCE(revoked_at, $2)
         WHERE user_id = $1::text::uuid",
        &[&user_id, &now],
    )
    .await?;
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: actor_id,
            action: "auth.password.changed",
            target: Some(user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: None,
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Upgrades an Argon2id work factor without invalidating a verified session.
/// The auth generation check prevents replacing a password changed concurrently.
pub async fn rehash_password(
    client: &mut Client,
    user_id: &str,
    expected_generation: i64,
    password_phc: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_credentials c SET password_phc = $3, changed_at = $4
             FROM console_users u
             WHERE c.user_id = u.user_id AND u.user_id = $1::text::uuid
               AND u.enabled AND u.auth_generation = $2",
            &[&user_id, &expected_generation, &password_phc, &now],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: user_id,
            action: "auth.password.rehashed",
            target: Some(user_id),
            result: "success",
            actor_kind: Some("user"),
            actor_id: Some(user_id),
            actor_display: None,
            authentication_method: Some("local_password"),
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: None,
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Disables an enabled user and revokes all sessions in one audited transaction.
pub async fn disable_local_user(
    client: &mut Client,
    user_id: &str,
    now: DateTime<Utc>,
    audit: &AuditContext<'_>,
    actor_id: &str,
    actor_kind: &str,
) -> Result<bool, StoreError> {
    let tx = client.transaction().await?;
    let updated = tx
        .execute(
            "UPDATE console_users SET enabled = false, disabled_at = $2,
                    auth_generation = auth_generation + 1
             WHERE user_id = $1::text::uuid AND enabled",
            &[&user_id, &now],
        )
        .await?;
    if updated == 0 {
        tx.rollback().await?;
        return Ok(false);
    }
    tx.execute(
        "UPDATE console_sessions SET revoked_at = COALESCE(revoked_at, $2)
         WHERE user_id = $1::text::uuid",
        &[&user_id, &now],
    )
    .await?;
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: actor_id,
            action: "user.disabled",
            target: Some(user_id),
            result: "success",
            actor_kind: Some(actor_kind),
            actor_id: Some(actor_id),
            actor_display: None,
            authentication_method: None,
            target_kind: Some("user"),
            target_id: Some(user_id),
            reason_code: Some("administrator_disabled"),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(true)
}

/// Stores hash-only one-use local pre-authentication state.
pub async fn create_preauth(client: &Client, state: &NewPreauth<'_>) -> Result<(), StoreError> {
    client
        .execute(
            "INSERT INTO console_preauth
                (token_sha256, csrf_sha256, browser_sha256, created_at, expires_at)
             VALUES ($1, $2, $3, $4, $5)",
            &[
                &state.token_sha256,
                &state.csrf_sha256,
                &state.browser_sha256,
                &state.created_at,
                &state.expires_at,
            ],
        )
        .await?;
    Ok(())
}

/// Atomically consumes pre-authentication state only when all three digests
/// match and it has not expired or been used.
pub async fn consume_preauth(
    client: &Client,
    token_sha256: &[u8],
    csrf_sha256: &[u8],
    browser_sha256: &[u8],
    now: DateTime<Utc>,
) -> Result<bool, StoreError> {
    let updated = client
        .execute(
            "UPDATE console_preauth SET consumed_at = $4
             WHERE token_sha256 = $1 AND csrf_sha256 = $2 AND browser_sha256 = $3
               AND expires_at > $4 AND consumed_at IS NULL",
            &[&token_sha256, &csrf_sha256, &browser_sha256, &now],
        )
        .await?;
    Ok(updated == 1)
}

/// Reports whether any account/source throttle bucket is currently locked.
pub async fn login_is_throttled(
    client: &Client,
    bucket_sha256: &[&[u8]],
    now: DateTime<Utc>,
) -> Result<bool, StoreError> {
    let row = client
        .query_one(
            "SELECT EXISTS (
                SELECT 1 FROM console_auth_throttle
                WHERE bucket_sha256 = ANY($1) AND locked_until > $2
             )",
            &[&bucket_sha256, &now],
        )
        .await?;
    Ok(row.get(0))
}

/// Records one failed login in every supplied bucket. Window, limit, and lock
/// duration are policy inputs held by the console configuration.
pub async fn record_login_failure(
    client: &mut Client,
    bucket_sha256: &[&[u8]],
    now: DateTime<Utc>,
    window: Duration,
    failure_limit: i32,
    lock_for: Duration,
    audit: &AuditContext<'_>,
) -> Result<(), StoreError> {
    let tx = client.transaction().await?;
    let window_cutoff = now - window;
    let locked_until = now + lock_for;
    for bucket in bucket_sha256 {
        tx.execute(
            "INSERT INTO console_auth_throttle
                (bucket_sha256, window_started_at, failures, locked_until, updated_at)
             VALUES ($1, $2, 1, CASE WHEN $4 <= 1 THEN $5::timestamptz END, $2)
             ON CONFLICT (bucket_sha256) DO UPDATE SET
                window_started_at = CASE
                    WHEN console_auth_throttle.window_started_at <= $3
                    THEN $2 ELSE console_auth_throttle.window_started_at END,
                failures = CASE
                    WHEN console_auth_throttle.window_started_at <= $3
                    THEN 1 ELSE console_auth_throttle.failures + 1 END,
                locked_until = CASE
                    WHEN console_auth_throttle.window_started_at <= $3
                        THEN CASE WHEN $4 <= 1 THEN $5::timestamptz END
                    WHEN console_auth_throttle.failures + 1 >= $4
                        THEN GREATEST(COALESCE(console_auth_throttle.locked_until, $2),
                                      $5)
                    ELSE console_auth_throttle.locked_until END,
                updated_at = $2",
            &[&bucket, &now, &window_cutoff, &failure_limit, &locked_until],
        )
        .await?;
    }
    append_auth_event(
        &tx,
        audit,
        AuthAuditEvent {
            actor: "console-login",
            action: "auth.login.failed",
            target: None,
            result: "failure",
            actor_kind: Some("anonymous"),
            actor_id: None,
            actor_display: None,
            authentication_method: Some("local_password"),
            target_kind: None,
            target_id: None,
            reason_code: Some("invalid_credentials"),
        },
    )
    .await?;
    tx.commit().await?;
    Ok(())
}

/// Clears successful login throttle buckets.
pub async fn clear_login_throttle(
    client: &Client,
    bucket_sha256: &[&[u8]],
    now: DateTime<Utc>,
) -> Result<(), StoreError> {
    client
        .execute(
            "UPDATE console_auth_throttle
             SET failures = 0, locked_until = NULL, window_started_at = $2, updated_at = $2
             WHERE bucket_sha256 = ANY($1)",
            &[&bucket_sha256, &now],
        )
        .await?;
    Ok(())
}

fn credential_from_row(row: &Row) -> Credential {
    Credential {
        user_id: row.get(0),
        username: row.get(1),
        display_name: row.get(2),
        password_phc: row.get(3),
        enabled: row.get(4),
        auth_generation: row.get(5),
    }
}

fn session_from_row(row: &Row) -> Session {
    Session {
        user_id: row.get(0),
        username: row.get(1),
        display_name: row.get(2),
        csrf_sha256: row.get(3),
        last_seen_at: row.get(4),
        idle_expires_at: row.get(5),
        absolute_expires_at: row.get(6),
    }
}

struct AuthAuditEvent<'a> {
    actor: &'a str,
    action: &'a str,
    target: Option<&'a str>,
    result: &'a str,
    actor_kind: Option<&'a str>,
    actor_id: Option<&'a str>,
    actor_display: Option<&'a str>,
    authentication_method: Option<&'a str>,
    target_kind: Option<&'a str>,
    target_id: Option<&'a str>,
    reason_code: Option<&'a str>,
}

async fn append_auth_event(
    tx: &tokio_postgres::Transaction<'_>,
    context: &AuditContext<'_>,
    event: AuthAuditEvent<'_>,
) -> Result<(), StoreError> {
    tx.execute(
        "INSERT INTO audit_log
            (actor, action, target, result, detail, request_id, actor_kind,
             actor_id, actor_display, authentication_method, target_kind,
             target_id, reason_code, source_address, user_agent)
         VALUES ($1, $2, $3, $4,
             CASE WHEN $12::text IS NULL THEN '{}'::jsonb
                  ELSE jsonb_build_object('reason_code', $12::text) END,
             $5, $6, $7, $8, $9, $10, $11, $12, $13::text::inet, $14)",
        &[
            &event.actor,
            &event.action,
            &event.target,
            &event.result,
            &context.request_id,
            &event.actor_kind,
            &event.actor_id,
            &event.actor_display,
            &event.authentication_method,
            &event.target_kind,
            &event.target_id,
            &event.reason_code,
            &context.source_address,
            &context.user_agent,
        ],
    )
    .await?;
    Ok(())
}
