//! Deterministic OpenAPI document generated from the Rust console contract.

use utoipa::OpenApi;

use crate::{
    api::{
        AccessAssetGroup, AccessBinding, AccessInventory, AccessRole, AccessUser, AgentDetail,
        AgentPage, AgentRuleSetView, AgentStatus, AgentSummary, AgentTagBindingImpact,
        AgentTagChangeRequest, AgentTagGroupImpact, AgentTagInput, AgentTagPreviewResponse,
        AgentView, ApplyAgentTagsRequest, AssetGroupSelectorInput, AuditEventPage, AuditEventView,
        AuditRetentionPolicy, AuthenticationLevel, AuthenticationMethod, CertificatePage,
        CertificateView, CreateAccessBindingRequest, CreateEnrollmentTokenRequest,
        CreatedEnrollmentToken, CursorPagination, CveDetailView, EffectiveCapability,
        EnrollmentTokenPage, EnrollmentTokenView, FindingHistoryEntry, FindingHistoryPage,
        FindingOrigin, FindingPage, FindingSummary, FindingView, LoginRequest, LoginResponse,
        Permission, PermissionScope, PreauthResponse, RevokeAgentRequest, SaveAssetGroupRequest,
        SessionPrincipal, SessionResponse, Severity, UpdateAuditRetentionRequest,
        VulnerabilityAdvisoryDetail, VulnerabilityPage, VulnerabilitySeverity,
        VulnerabilitySeverityCount, VulnerabilitySummary, VulnerabilityTopHost, VulnerabilityView,
    },
    problem::{FieldError, ProblemDetails},
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "OpenVIBES Console API",
        version = "1.0.0",
        description = "Versioned human and service-account API for the OpenVIBES console.",
        license(name = "MIT")
    ),
    paths(
        crate::router::create_authenticated_asset_group,
        crate::router::update_authenticated_asset_group,
        crate::router::revoke_authenticated_agent,
        crate::router::authenticated_enrollment_tokens,
        crate::router::authenticated_agent_package,
        crate::router::authenticated_enrollment_token,
        crate::router::create_authenticated_enrollment_token,
        crate::router::revoke_authenticated_enrollment_token,
        crate::router::authenticated_service_accounts,
        crate::router::create_authenticated_service_account,
        crate::users::create_user,
        crate::users::change_password,
        crate::router::disable_authenticated_service_account,
        crate::router::authenticated_service_tokens,
        crate::router::create_authenticated_service_token,
        crate::router::revoke_authenticated_service_token,
        crate::router::authenticated_rule_sets,
        crate::router::authenticated_rule_bundles,
        crate::router::preview_authenticated_rule_bundle,
        crate::router::publish_authenticated_rule_bundle,
        crate::router::preview_authenticated_agent_tags,
        crate::router::apply_authenticated_agent_tags,
        crate::router::authenticated_access_inventory,
        crate::router::create_authenticated_access_binding,
        crate::router::revoke_authenticated_access_binding,
        crate::router::session,
        crate::router::authenticated_assistant_status,
        crate::router::authenticated_assistant_message,
        crate::router::preauth,
        crate::router::login,
        crate::router::logout,
        crate::about::about,
        crate::about::about_update,
        crate::router::authenticated_agent_summary,
        crate::router::authenticated_agents,
        crate::router::authenticated_agent_detail,
        crate::router::authenticated_agent_certificates,
        crate::router::authenticated_finding_summary,
        crate::router::authenticated_latest_findings,
        crate::router::authenticated_latest_finding,
        crate::router::authenticated_finding_triage,
        crate::router::update_authenticated_finding_triage,
        crate::router::authenticated_finding_history,
        crate::router::authenticated_finding_event,
        crate::router::authenticated_finding_groups,
        crate::router::authenticated_finding_group_endpoints,
        crate::router::update_authenticated_finding_group_triage,
        crate::router::authenticated_vulnerability_summary,
        crate::router::authenticated_vulnerabilities,
        crate::router::authenticated_vulnerability_advisory,
        crate::router::authenticated_audit_retention,
        crate::router::authenticated_audit_events,
        crate::router::authenticated_audit_export,
        crate::router::update_authenticated_audit_retention,
        crate::dashboards::list_dashboards,
        crate::dashboards::create_dashboard,
        crate::dashboards::get_dashboard,
        crate::dashboards::update_dashboard,
        crate::dashboards::delete_dashboard,
        crate::dashboards::share_dashboard,
        crate::dashboards::get_home,
        crate::dashboards::set_home,
        crate::software::list_host_packages,
        crate::software::list_software,
        crate::software::get_software,
        crate::ports::get_host_services,
        crate::ports::list_ports,
        crate::ports::list_services,
        crate::ports::get_port,
        crate::ports::get_unit,
        crate::alarms::list_alarms,
        crate::alarms::get_alarm,
        crate::alarms::update_alarm_triage,
        crate::alarm_suppressions::list_suppressions,
        crate::alarm_suppressions::create_suppression,
        crate::alarm_suppressions::remove_suppression,
        crate::cases::list_cases,
        crate::cases::create_case,
        crate::cases::cases_for_item,
        crate::cases::list_assignees,
        crate::cases::get_case,
        crate::cases::update_case,
        crate::cases::add_note,
        crate::cases::add_item,
        crate::cases::remove_item,
        crate::cases::set_item_outcome
    ),
    components(schemas(
        crate::software::HostPackageView,
        crate::software::HostPackagePage,
        crate::software::SoftwareView,
        crate::software::SoftwarePage,
        crate::software::SoftwareVersionView,
        crate::software::SoftwareAdvisoryView,
        crate::software::SoftwareHostView,
        crate::software::SoftwareDetail,
        crate::ports::ListenerView,
        crate::ports::ServiceView,
        crate::ports::HostServicesView,
        crate::ports::PortView,
        crate::ports::UnitView,
        crate::ports::PortHostView,
        crate::ports::PortDetail,
        crate::ports::UnitHostView,
        crate::ports::UnitDetail,
        crate::alarms::AlarmSummaryView,
        crate::alarms::AlarmPage,
        crate::alarms::AlarmTriageView,
        crate::alarms::AlarmDetailView,
        crate::alarms::UpdateAlarmTriageRequest,
        crate::alarm_suppressions::AlarmSuppressionView,
        crate::alarm_suppressions::AlarmSuppressionList,
        crate::alarm_suppressions::CreateAlarmSuppressionRequest,
        crate::cases::CaseUserView,
        crate::cases::CaseSummaryView,
        crate::cases::CasePage,
        crate::cases::CaseItemView,
        crate::cases::CaseEventView,
        crate::cases::CaseDetailView,
        crate::cases::ItemCaseView,
        crate::cases::ItemCasesView,
        crate::cases::CaseAssigneesView,
        crate::cases::CaseItemRef,
        crate::cases::CreateCaseRequest,
        crate::cases::UpdateCaseRequest,
        crate::cases::AddCaseNoteRequest,
        crate::cases::SetCaseItemOutcomeRequest,
        crate::api::DashboardView,
        crate::api::DashboardPage,
        crate::api::SaveDashboardRequest,
        crate::api::ShareDashboardRequest,
        crate::api::HomeDashboard,
        AssetGroupSelectorInput,
        SaveAssetGroupRequest,
        RevokeAgentRequest,
        CreateEnrollmentTokenRequest,
        CreatedEnrollmentToken,
        EnrollmentTokenPage,
        EnrollmentTokenView,
        AgentTagBindingImpact,
        AgentTagChangeRequest,
        AgentTagGroupImpact,
        AgentTagInput,
        AgentTagPreviewResponse,
        ApplyAgentTagsRequest,
        AccessAssetGroup,
        AccessBinding,
        AccessInventory,
        AccessRole,
        AccessUser,
        CreateAccessBindingRequest,
        AuthenticationLevel,
        AuthenticationMethod,
        AuditRetentionPolicy,
        AuditEventPage,
        AuditEventView,
        AuditRetentionPolicy,
        AgentDetail,
        AgentPage,
        AgentStatus,
        AgentSummary,
        AgentView,
        AgentRuleSetView,
        LoginRequest,
        crate::ChangePasswordRequest,
        crate::CreateUserRequest,
        crate::CreatedUser,
        LoginResponse,
        CertificatePage,
        CertificateView,
        CursorPagination,
        EffectiveCapability,
        FieldError,
        FindingHistoryEntry,
        FindingHistoryPage,
        crate::api::FindingGroupView,
        crate::api::FindingGroupPage,
        crate::api::FindingGroupEndpointView,
        crate::api::FindingGroupEndpointPage,
        crate::api::BulkFindingTriageChange,
        crate::api::BulkFindingTriageRequest,
        crate::api::BulkFindingTriageResponse,
        FindingOrigin,
        FindingPage,
        FindingSummary,
        FindingView,
        CveDetailView,
        VulnerabilityAdvisoryDetail,
        VulnerabilityPage,
        VulnerabilitySeverity,
        VulnerabilitySeverityCount,
        VulnerabilitySummary,
        VulnerabilityTopHost,
        VulnerabilityView,
        crate::api::FindingTriageView,
        crate::api::UpdateFindingTriageRequest,
        crate::assistant::ClientTurn,
        crate::assistant::AssistantMessageRequest,
        crate::assistant::AssistantSegment,
        crate::assistant::AssistantLookup,
        crate::assistant::AssistantMessageResponse,
        crate::assistant::AssistantStatusResponse,
        crate::about::AboutResponse,
        crate::about::AboutFleet,
        crate::about::AboutCertificate,
        crate::about::AboutFeed,
        crate::about::UpdateResponse,
        crate::about::UpdateState,
        Permission,
        PermissionScope,
        PreauthResponse,
        ProblemDetails,
        SessionPrincipal,
        SessionResponse,
        UpdateAuditRetentionRequest,
        UpdateAuditRetentionRequest,
        Severity
    )),
    tags(
        (name = "session", description = "Current browser session"),
        (name = "authentication", description = "Local browser authentication"),
        (name = "about", description = "Platform versions and newer-release check"),
        (name = "agents", description = "Scope-filtered agent reads"),
        (name = "alarms", description = "Scope-filtered threat alarms and their triage"),
        (name = "cases", description = "Investigations: items, notes, assignment and closing, scope-filtered"),
        (name = "software", description = "Installed software per host and across the caller's hosts"),
        (name = "assets", description = "Open ports and running services per host and across the caller's hosts"),
        (name = "findings", description = "Scope-filtered observation reads"),
        (name = "vulnerabilities", description = "Scope-filtered vulnerability review"),
        (name = "assistant", description = "Read-only local assistant"),
        (name = "audit", description = "Audit policy and event access")
    )
)]
struct ConsoleApi;

/// Returns the generated OpenAPI 3 document.
pub fn document() -> utoipa::openapi::OpenApi {
    ConsoleApi::openapi()
}

/// Serializes the generated document deterministically as pretty JSON.
pub fn json() -> Result<String, serde_json::Error> {
    let mut output = serde_json::to_string_pretty(&document())?;
    output.push('\n');
    Ok(output)
}
